const {chromium,request}=require('playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');const {randomUUID}=require('node:crypto');
(async()=>{
 const base='http://127.0.0.1:5173',results=[];const test=async(name,fn)=>{await fn();results.push(name);console.log('PASS',name);};
 const admin=await request.newContext({baseURL:base,extraHTTPHeaders:{Origin:base}}),member=await request.newContext({baseURL:base,extraHTTPHeaders:{Origin:base}}),anon=await request.newContext({baseURL:base,extraHTTPHeaders:{Origin:base}});
 async function post(c,path,data,expected=200){const r=await c.post('/api/'+path,{data});const j=await r.json();assert.equal(r.status(),expected,JSON.stringify(j));return j;}
 const state=async c=>(await c.get('/api/state')).json();
 await post(admin,'preview-login',{role:'admin'});await post(member,'preview-login',{role:'member'});
 await test('Private guild records require authentication',async()=>assert.equal((await anon.get('/api/state')).status(),401));
 await test('Members cannot call administrator endpoints',async()=>await post(member,'admin/settings',{weekly:500000,rate:20,notice:'No'},403));
 await test('Cross-origin writes are blocked',async()=>{const r=await member.post('/api/deposit',{headers:{Origin:'https://unrelated.example'},data:{}});assert.equal(r.status(),403);});
 await test('Invalid forms return a useful validation error',async()=>await post(member,'bid',{id:'invalid',auctionId:'wrong',amount:-1},400));
 const auctionId=randomUUID();await post(admin,'admin/auction',{id:auctionId,itemId:'poison',upgrade:0,quantity:1,source:'Demon Tower',bonuses:'',minimum:200,increment:20,hours:24});
 let a=(await state(admin)).auctions.find(a=>a.id===auctionId);let start=a.current?a.current+a.increment:a.minimum;
 const bidID=randomUUID();await test('Real bid reserves PP on server',async()=>{await post(member,'bid',{id:bidID,auctionId:a.id,amount:start});const s=await state(member);assert.equal(s.auctions.find(x=>x.id===a.id).current,start);assert.ok(s.member.reserved>=start);});
 await test('Bid retry is idempotent',async()=>{const old=(await state(member)).member.reserved;await post(member,'bid',{id:bidID,auctionId:a.id,amount:start});assert.equal((await state(member)).member.reserved,old);});
 await test('Same bid request ID cannot be reused for a different amount',async()=>await post(member,'bid',{id:bidID,auctionId:a.id,amount:start+20},409));
 await test('Concurrent equal bids produce one winner',async()=>{const amount=start+20;const rs=await Promise.all([admin.post('/api/bid',{data:{id:randomUUID(),auctionId:a.id,amount}}),member.post('/api/bid',{data:{id:randomUUID(),auctionId:a.id,amount}})]);assert.equal(rs.filter(r=>r.status()===200).length,1);assert.equal(rs.filter(r=>r.status()===409).length,1);assert.equal((await state(admin)).auctions.find(x=>x.id===a.id).current,amount);});
 await test('Overspending is rejected without corrupting balances',async()=>await post(member,'bid',{id:randomUUID(),auctionId:a.id,amount:999980},409));
 let d=randomUUID(),before=(await state(member)).member.balance;
 await test('Donation stays pending without awarding PP',async()=>{await post(member,'deposit',{id:d,kind:'donation',yang:1000000,note:'Browser QA donation'});const s=await state(member);assert.equal(s.member.balance,before);assert.equal(s.deposits.find(x=>x.id===d).status,'pending');});
 await test('Repeated donation does not create a duplicate',async()=>{await post(member,'deposit',{id:d,kind:'donation',yang:1000000,note:'Browser QA donation'});assert.equal((await state(member)).deposits.filter(x=>x.id===d).length,1);});
 await test('Admin approval awards PP once',async()=>{await post(admin,'admin/deposit',{id:d,status:'approved'});assert.equal((await state(member)).member.balance,before+40);await post(admin,'admin/deposit',{id:d,status:'approved'},409);assert.equal((await state(member)).member.balance,before+40);});
 const e=(await state(member)).events.find(e=>e.status==='upcoming'&&e.starts>Date.now()/1000);
 await test('RSVP and event-specific reminder persist',async()=>{await post(member,'event',{eventId:e.id,joined:true,reminder:30});const s=await state(member);assert.equal(s.events.find(x=>x.id===e.id).joined,1);assert.equal(s.events.find(x=>x.id===e.id).reminder,30);assert.equal(s.member.balance,before+40);});
 await test('Future event cannot award participation PP early',async()=>await post(admin,'admin/finalize-event',{id:e.id,status:'completed'},409));
 const past=(await state(admin)).events.find(e=>e.status==='upcoming'&&e.starts<Date.now()/1000);
 if(past){await test('Confirmed attendance awards PP exactly once',async()=>{await post(admin,'admin/attendance',{eventId:past.id,memberId:'preview-member',attended:true});const b=(await state(member)).member.balance;await post(admin,'admin/finalize-event',{id:past.id,status:'completed'});assert.equal((await state(member)).member.balance,b+past.pp);await post(admin,'admin/finalize-event',{id:past.id,status:'completed'},409);assert.equal((await state(member)).member.balance,b+past.pp);});}
 await test('Auction cancellation releases reservations',async()=>{await post(admin,'admin/cancel-auction',{id:a.id});const s=await state(member);assert.equal(s.auctions.find(x=>x.id===a.id).status,'cancelled');await post(member,'bid',{id:randomUUID(),auctionId:a.id,amount:start+40},409);});
 await test('Image upload rejects disguised HTML',async()=>{const r=await admin.post('/api/admin/item',{multipart:{name:'Bad',height:'1',level:'0',classes:'Warrior',icon:{name:'bad.png',mimeType:'image/png',buffer:Buffer.from('<script>alert(1)</script>')}}});assert.equal(r.status(),400);});
 await test('Native catalogue import preserves item image mapping',async()=>{await post(admin,'admin/catalogue',{});const s=await state(admin);assert.equal(s.items.find(i=>i.name==='Poison Sword').icon,'/metin2/poison.png');assert.equal(s.items.find(i=>i.name==='Dragon God Armour').classes,'Warrior');});
 await test('Protected scheduler rejects unauthorized requests',async()=>await post(anon,'jobs/tick',{},403));
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},storageState:await admin.storageState()});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByRole('navigation',{name:'Guild navigation'}).waitFor();
 const screens=['Guild Hall','My Character','Auction House','Events','Treasury','Administration'];const widths=[320,375,390,768,1024,1440],layouts=[];
 fs.mkdirSync('tests/screenshots',{recursive:true});
 for(const width of widths){await page.setViewportSize({width,height:900});for(const name of screens){await page.getByRole('button',{name,exact:true}).click();await page.locator('.pg-main h2').waitFor();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);assert.equal(overflow,false,`${name} at ${width} overflows`);const clipped=await page.locator('.pg-window button').evaluateAll(nodes=>nodes.filter(n=>{const r=n.getBoundingClientRect(),w=n.closest('.pg-window').getBoundingClientRect();return r.width>0&&(r.left<w.left-1||r.right>w.right+1)}).map(n=>n.textContent));assert.deepEqual(clipped,[],`${name} at ${width} clips buttons`);const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>i.complete&&!i.naturalWidth).map(i=>i.src));assert.deepEqual(broken,[],`${name} at ${width} broken images`);layouts.push({name,width});if([390,1440].includes(width))await page.screenshot({path:`tests/screenshots/${width}-${name.toLowerCase().replaceAll(' ','-')}.png`,fullPage:true});}}
 results.push('36 responsive screen layouts without overflow or broken images');console.log('PASS 36 responsive layouts');
 await test('Only one navigation bar exists',async()=>assert.equal(await page.locator('nav').count(),1));
 await test('Native modal traps focus, closes with Escape and returns focus',async()=>{await page.getByRole('button',{name:'Aether',exact:true}).click();await page.locator('dialog').waitFor({state:'visible'});await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>!!document.activeElement.closest('dialog')),true);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').isVisible(),false);assert.equal(await page.getByRole('button',{name:'Aether',exact:true}).evaluate(n=>n===document.activeElement),true);});
 await test('Mobile donation form submits real records',async()=>{const note='Mobile QA '+randomUUID().slice(0,8);await page.setViewportSize({width:390,height:900});await page.getByRole('button',{name:'Treasury',exact:true}).click();await page.getByRole('button',{name:'My Deposits',exact:true}).click();await page.getByLabel('Yang Amount').fill('250000');await page.getByLabel('Deposit Note (optional)').fill(note);await page.getByRole('button',{name:'Submit Donation',exact:true}).click();await page.getByRole('status').filter({hasText:'Donation submitted'}).waitFor();assert.equal(await page.getByText(note,{exact:true}).count(),1);});
 await test('Installable PWA manifest and service worker are present',async()=>{const m=await (await admin.get('/manifest.webmanifest')).json();assert.equal(m.display,'standalone');assert.equal(m.icons.length,2);const sw=await admin.get('/sw.js');assert.equal(sw.status(),200);assert.ok((await sw.text()).includes("url.pathname.startsWith('/api/')"));});
 const memberContext=await browser.newContext({storageState:await member.storageState()});const memberPage=await memberContext.newPage();await memberPage.goto(base);await memberPage.getByRole('navigation').waitFor();await test('Member UI hides administrator navigation',async()=>assert.equal(await memberPage.getByRole('button',{name:'Administration',exact:true}).count(),0));
 await test('No browser runtime exceptions',async()=>assert.deepEqual(errors,[]));
 fs.writeFileSync('tests/browser-results.json',JSON.stringify({checks:results,layouts,errors},null,2));console.log(results.length+' API/UI checks passed');await browser.close();await Promise.all([admin.dispose(),member.dispose(),anon.dispose()]);
})().catch(e=>{console.error(e);process.exit(1)});
