import assert from 'node:assert/strict';
import {tmpdir} from 'node:os';
import path from 'node:path';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.GUIDE_TEST_ORIGIN||'http://127.0.0.1:3177';
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});
const topics=[['phone',3],['notifications',4],['events',3],['help',5],['experienced',4],['auctions',3],['points',3],['administrators',3]];
try{for(const width of [320,390,768,1440]){
 const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'}),page=await context.newPage(),errors=[],privateRequests=[],images=new Set();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))privateRequests.push(r.url());});
 assert.equal((await page.goto(base+'/how-to-use')).status(),200);await page.getByRole('heading',{name:'How to Use',exact:true}).waitFor();assert.equal(await page.title(),'How to Use — Paragon');assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('.pg-nav').count(),0);assert.equal(await page.locator('.pg-guide-topic-list a').count(),8);assert.equal(await page.locator('.pg-guide-viewer').count(),0);assert.doesNotMatch(await page.locator('main').innerText(),/Chrome|Android/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.className),'pg-skip');assert.ok(await page.evaluate(()=>parseFloat(getComputedStyle(document.activeElement).outlineWidth)>=2));await page.screenshot({path:path.join(tmpdir(),'paragon-simple-guide-index-'+width+'.png')});
 for(const [id,total] of topics){
  if(width<=700&&await page.locator('.pg-guide-viewer').count())await page.locator('.pg-guide-back').click();await page.locator('.pg-guide-topic-list a[href="#'+id+'"]').click();await page.getByRole('status').getByText('Step 1 of '+total,{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.activeElement.tagName),'H2');if(width<=700)assert.equal(await page.locator('.pg-guide-index').isVisible(),false);
  for(let i=1;i<=total;i++){
   assert.equal(await page.locator('.pg-guide-instruction').count(),1);assert.equal(await page.locator('.pg-guide-screen img').count(),1);await page.getByRole('status').getByText('Step '+i+' of '+total,{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Back',exact:true}).isDisabled(),i===1);const image=page.locator('.pg-guide-screen img');await image.scrollIntoViewIfNeeded();await image.evaluate(e=>e.decode());images.add(await image.getAttribute('src'));assert.ok(await image.evaluate(e=>e.naturalWidth>0));assert.equal(await image.locator('..').getAttribute('target'),'_blank');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,id+' step '+i+' overflow '+width);
   if(id==='experienced'&&i===1){await page.getByRole('heading',{name:'Schedule Demon Tower',exact:true}).waitFor();assert.equal(await image.getAttribute('src'),'/guide/demon-tower.png');assert.match(await page.locator('.pg-guide-note').innerText(),/10 PP/);assert.match(await page.locator('.pg-guide-note').innerText(),/No end time/);}
   if(id==='experienced'&&i===2){await page.getByRole('heading',{name:'Make a Custom event',exact:true}).waitFor();assert.match(await page.locator('.pg-guide-copy').innerText(),/title, CH, PP and start time/);await page.screenshot({path:path.join(tmpdir(),'paragon-simple-guide-custom-'+width+'.png')});}
   if(id==='events'&&i===3){await page.getByText('PP rewards',{exact:true}).click();assert.deepEqual(await page.locator('.pg-guide-extra dd').allTextContents(),['10 PP','10 PP','35 PP','100 PP','100 PP','75 PP','Chosen by host']);}
   if(i<total){await page.getByRole('button',{name:'Next Step →',exact:true}).click();await page.waitForFunction(({id,step})=>location.hash==='#'+id+'/'+step,{id,step:i+1});}else assert.equal(await page.getByRole('button',{name:'Done',exact:true}).count(),1);
  }
 }
 assert.equal(images.size,16,'all 16 real screenshot assets covered');await page.getByRole('button',{name:'Done',exact:true}).click();await page.locator('.pg-guide-viewer').waitFor({state:'hidden'});assert.equal(await page.locator('.pg-guide-index').isVisible(),true);assert.equal(await page.evaluate(()=>document.activeElement.id),'pg-guide-index-title');
 await page.goto(base+'/how-to-use#help/4');await page.getByRole('heading',{name:'Choose who attended',exact:true}).waitFor();await page.getByRole('button',{name:'Back',exact:true}).press('Space');await page.getByRole('heading',{name:'Tap End Event',exact:true}).waitFor();await page.goBack();await page.getByRole('heading',{name:'Choose who attended',exact:true}).waitFor();await page.reload();await page.getByRole('heading',{name:'Choose who attended',exact:true}).waitFor();
 for(const [hash,title] of [['#help/2.5','Create a Help request'],['#help/0','Create a Help request'],['#help/99','Submit for Approval'],['#notifications','Open notification settings']]){await page.goto(base+'/how-to-use'+hash);await page.getByRole('heading',{name:title,exact:true}).waitFor();}await page.goto(base+'/how-to-use#missing');await page.locator('.pg-guide-topic-list a').first().waitFor();assert.equal(await page.locator('.pg-guide-viewer').count(),0);
 assert.deepEqual(errors,[]);assert.deepEqual(privateRequests,[]);await context.close();console.log('PASS '+width+'px: eight topics, one step/screenshot at a time, all 16 images, next/back/done, keyboard focus, direct step links, browser back/reload, malformed hash fallback, current PP and no private API calls.');
}
// Pointer navigation keeps the same button, geometry and viewport through every step.
for(const width of [320,390,768,1440]){
 const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'no-preference'}),page=await context.newPage();
 await page.goto(base+'/how-to-use#phone/1');await page.getByRole('heading',{name:'Open Paragon in Safari',exact:true}).waitFor();
 const next=page.locator('.pg-guide-controls button').last();await next.scrollIntoViewIfNeeded();
 await page.evaluate(()=>globalThis.__guideButton=document.querySelector('.pg-guide-controls button:last-child'));
 const read=()=>next.evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,scroll:scrollY,transform:getComputedStyle(e).transform};});
 const before=await read();const box=await next.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();assert.deepEqual(await read(),before,'mouse down changes guide button geometry');await page.mouse.up();
 await page.getByRole('heading',{name:'Add it to your Home Screen',exact:true}).waitFor();assert.deepEqual(await read(),before,'step 1→2 moved controls/viewport');assert.equal(await page.evaluate(()=>document.querySelector('.pg-guide-controls button:last-child')===globalThis.__guideButton),true);assert.equal(await next.evaluate(e=>document.activeElement===e),true);
 await next.press('Enter');await page.getByRole('heading',{name:'Open the Paragon icon',exact:true}).waitFor();assert.deepEqual(await read(),before,'step 2→3 moved controls/viewport');assert.equal(await next.innerText(),'Done');assert.equal(await next.evaluate(e=>document.activeElement===e),true);assert.equal(await page.evaluate(()=>document.querySelector('.pg-guide-controls button:last-child')===globalThis.__guideButton),true);
 await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByRole('heading',{name:'Add it to your Home Screen',exact:true}).waitFor();assert.deepEqual(await read(),before,'Back moved controls/viewport');
 await page.screenshot({path:path.join(tmpdir(),'paragon-stable-guide-controls-'+width+'.png')});await context.close();console.log('PASS '+width+'px: no motion preference, stable press/step/back geometry and viewport, same forward button through Done, keyboard focus preserved.');
}
}finally{await browser.close();}
