import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:3190',dictionary=JSON.parse(readFileSync(new URL('../lib/translations.json',import.meta.url),'utf8'));
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});
const label=(key,language)=>language==='en'?key:dictionary[key]?.[language]??key;
const topics=[['phone',3],['notifications',4],['events',3],['help',5],['experienced',4],['auctions',3],['points',3],['administrators',3]];
try{
for(const width of [320,390,1440])for(const language of ['en','tr','el']){
 const context=await browser.newContext({viewport:{width,height:1000},timezoneId:'America/New_York'}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
 const L=key=>label(key,language),choose=async lang=>{await page.locator('select[name=language]').selectOption(lang);await page.waitForFunction(expected=>document.documentElement.lang===expected,lang);};
 await context.request.post(base+'/api/demo-login',{headers:{Origin:base},data:{role:'leader'}});
 await page.goto(base+'/?view=home');await page.locator('.pg-nav').waitFor();await choose(language);await page.getByRole('heading',{name:L('Guild Home'),exact:true}).waitFor();assert.equal(await page.locator('.pg-nav').innerText(),['Home','Auctions','Events','Profile'].map(L).join('\n'));
 assert.equal(await page.locator('.pg-character img').count(),0);assert.equal(await page.locator('.pg-character-window img').getAttribute('src'),'/metin2/shaman.png','localized class must not change image identity');
 const state=await(await context.request.get(base+'/api/state')).json();
 for(const view of ['profile','auctions','events','admin']){await page.locator('.pg-nav button').nth(view==='profile'?3:view==='auctions'?1:2).click();if(view==='admin')await page.goto(base+'/?view=admin');await page.locator('.pg-main').waitFor();await page.waitForFunction(expected=>document.documentElement.lang===expected,language);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,language+' '+view+' '+width);}
 await page.goto(base+'/?view=events&create=1');const create=page.locator('.pg-create-dialog[open]');await create.waitFor();await create.locator('input[name=title]').fill('Authored title — stays unchanged');await create.locator('select[name=location]').selectOption('Spider Dungeon 2');await create.locator('select[name=gameChannel]').selectOption('6');await create.locator('input[name=durationMinutes]').fill('75');
 // Changing language must not remount or clear a form. Programmatic dispatch models the native select while the dialog is modal.
 await page.locator('select[name=language]').evaluate((select,language)=>{select.value=language;select.dispatchEvent(new Event('change',{bubbles:true}));},language==='el'?'tr':'el');await page.waitForFunction(expected=>document.documentElement.lang===expected,language==='el'?'tr':'el');assert.equal(await create.locator('input[name=title]').inputValue(),'Authored title — stays unchanged');assert.equal(await create.locator('select[name=location]').inputValue(),'Spider Dungeon 2');await page.locator('select[name=language]').evaluate((select,language)=>{select.value=language;select.dispatchEvent(new Event('change',{bubbles:true}));},language);await page.waitForFunction(expected=>document.documentElement.lang===expected,language);
 assert.equal(await create.locator('select[name=kind]').inputValue(),'Help');assert.equal(await create.evaluate(element=>element.scrollWidth<=element.clientWidth),true,'create modal overflow');await create.getByRole('button',{name:L('Start Help Event'),exact:true}).click();await page.getByText(L('Event created.'),{exact:true}).waitFor();const current=await(await context.request.get(base+'/api/state')).json(),event=current.events.find(e=>e.title==='Authored title — stays unchanged');assert.equal(event.kind,'Help');assert.equal(event.pp,10);assert.equal(event.location,'Spider Dungeon 2');assert.equal(event.game_channel,6);assert.equal(event.duration_minutes,75);assert.equal(current.member.balance,state.member.balance);
 await page.goto(base+'/?view=events&event='+event.id);await page.locator('.pg-event-dialog[open]').waitFor();await page.locator('.pg-event-dialog h3').getByText(event.title,{exact:true}).waitFor();await page.locator('.pg-event-dialog').getByRole('button',{name:L('Close'),exact:true}).click();
 await page.goto(base+'/?view=auctions');await page.getByRole('button',{name:L('Place Bid'),exact:false}).first().click();const bid=page.locator('.pg-dialog[open]');await bid.locator('input[name=amount]').fill('300');assert.equal(await bid.locator('input[name=amount]').inputValue(),'300');
 await page.route('**/api/bid',route=>route.fulfill({status:409,json:{error:'Not enough available PP'}}));await bid.getByRole('button',{name:L('Confirm Bid'),exact:true}).click();await bid.getByRole('alert').getByText(L('Not enough available PP'),{exact:true}).waitFor();await page.unroute('**/api/bid');await bid.getByRole('button',{name:L('Confirm Bid'),exact:true}).click();await page.getByText(L('Bid placed. Your PP reservation has been updated.'),{exact:true}).waitFor();const after=await(await context.request.get(base+'/api/state')).json();assert.equal(after.member.balance,state.member.balance);assert.equal(after.member.reserved,300);
 await page.goto(base+'/?view=admin');await page.getByRole('radio').first().check();await page.locator('input[name=amount]').fill('10');await page.locator('textarea[name=note]').fill('i18n isolated demo test');const player=await page.locator('.pg-grant-recipient strong').innerText();await page.locator('.pg-grant-form').getByRole('button',{name:L('Add PP'),exact:true}).click();await page.locator('.pg-admin-points > section > [role=status]').waitFor();assert.ok((await page.locator('.pg-admin-points > section > [role=status]').innerText()).includes(player));await page.locator('select[name=operation]').selectOption('remove');await page.locator('input[name=amount]').fill('10');await page.locator('textarea[name=note]').fill('Reverse i18n isolated demo test');await page.getByRole('button',{name:L('Remove PP'),exact:true}).click();await page.getByRole('button',{name:L('Confirm Removal'),exact:true}).click();await page.locator('.pg-adjustment-confirm').waitFor({state:'hidden'});
 await page.goto(base+'/how-to-use#help/1');await page.getByRole('heading',{name:L('Create a Help request'),exact:true}).waitFor();assert.equal(await page.locator('.pg-guide-count').innerText(),label('Step {current} of {total}',language).replace('{current}','1').replace('{total}','5')+'\n: '+L('Create a Help request'));assert.equal(await page.locator('.pg-guide-controls button').last().innerText(),L('Next Step →'));await page.locator('.pg-guide-controls button').last().click();await page.getByRole('heading',{name:L('Upload your screenshot'),exact:true}).waitFor();await page.reload();await page.getByRole('heading',{name:L('Upload your screenshot'),exact:true}).waitFor();assert.equal(await page.locator('select[name=language]').inputValue(),language);
 // Every guide step and image at every supported width in every language.
 for(const [id,total] of topics){await page.goto(base+'/how-to-use#'+id+'/1');await page.locator('.pg-guide-viewer').waitFor();for(let i=0;i<total;i++){const image=page.locator('.pg-guide-screen img');await image.evaluate(image=>image.decode());assert.ok(await image.evaluate(image=>image.naturalWidth>0));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,language+' guide '+id+' step '+i+' '+width);if(i<total-1)await page.locator('.pg-guide-controls button').last().click();}await page.locator('.pg-guide-controls button').last().click();await page.locator('.pg-guide-viewer').waitFor({state:'hidden'});}
 await page.goto(base+'/how-to-use#phone/1');await page.locator('.pg-guide-viewer').waitFor();await page.screenshot({path:'/private/tmp/paragon-language-'+language+'-'+width+'.png'});assert.deepEqual(errors,[]);await context.close();console.log('PASS '+language+' '+width+'px: native picker, all views, persisted locale, no overflow, unchanged draft/protocol/assets/user text, real Help creation, translated bid error, real bid reservation, admin add/remove and all guide steps/images.');
}
// Browser preference, invalid persisted preference and cross-tab synchronization.
for(const [locale,saved,expected] of [['tr-TR',null,'tr'],['el-GR','invalid','el'],['tr-TR','en','en']]){
 const context=await browser.newContext({locale}),page=await context.newPage();if(saved)await page.addInitScript(value=>localStorage.setItem('paragon-language',value),saved);await page.goto(base+'/how-to-use');await page.waitForFunction(language=>document.documentElement.lang===language,expected);const other=await context.newPage();await other.goto(base+'/how-to-use');await page.locator('select[name=language]').selectOption('el');await other.waitForFunction(()=>document.documentElement.lang==='el');await context.close();
}
console.log('PASS browser language defaults, explicit preference precedence, invalid preference fallback and cross-tab sync.');
}finally{await browser.close();}
