import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));db.exec('PRAGMA foreign_keys=ON');
const now=Math.floor(Date.now()/1000);let checks=0;
const q=(s,...a)=>db.prepare(s).get(...a),run=(s,...a)=>db.prepare(s).run(...a),test=(name,fn)=>{fn();checks++;console.log('PASS',name);};
for(const id of ['a','b','c'])run("INSERT INTO members(id,name,class,created) VALUES(?,?,'Shaman',?)",id,id,now);
run("INSERT INTO items(id,name,icon,height,classes,created) VALUES('sword','Poison Sword','/metin2/poison.png',2,'Sura',?)",now);
for(const member of ['a','b'])run("INSERT INTO ledger VALUES(?,?,1000,'PvE','Earned PP',?)",'seed:'+member,member,now);
function auction(id,ends=now+1000){run("INSERT INTO auctions(id,item_id,upgrade,source,bonuses,minimum,increment,starts,ends,created_by,created) VALUES(?,'sword',0,'Demon Tower','',100,20,?,?, 'a',?)",id,now-100,ends,now);}
function bid(id,member,amount,auctionId='one'){run('INSERT INTO bids VALUES(?,?,?,?,?)',id,auctionId,member,amount,now);}
auction('one');auction('two');
test('First bid reserves PP without spending balance',()=>{bid('b1','a',100);assert.equal(q("SELECT reserved FROM members WHERE id='a'").reserved,100);assert.equal(q("SELECT balance FROM members WHERE id='a'").balance,1000);});
test('Invalid increment rolls back the entire bid',()=>{assert.throws(()=>bid('bad','b',130));assert.equal(q("SELECT current FROM auctions WHERE id='one'").current,100);assert.equal(q("SELECT reserved FROM members WHERE id='b'").reserved,0);});
test('Outbid releases old member and reserves new member atomically',()=>{bid('b2','b',140);assert.equal(q("SELECT reserved FROM members WHERE id='a'").reserved,0);assert.equal(q("SELECT reserved FROM members WHERE id='b'").reserved,140);});
test('Raising bid replaces own reservation',()=>{bid('b3','b',180);assert.equal(q("SELECT reserved FROM members WHERE id='b'").reserved,180);});
test('Reservations across auctions cannot exceed balance',()=>{bid('b4','b',800,'two');assert.throws(()=>bid('b5','b',240));assert.equal(q("SELECT reserved FROM members WHERE id='b'").reserved,980);});
test('Member without PP cannot bid',()=>assert.throws(()=>bid('b6','c',260)));
test('Repeating a request cannot duplicate a bid',()=>{assert.throws(()=>bid('b3','b',180));assert.equal(q("SELECT COUNT(*) n FROM bids WHERE id='b3'").n,1);});
test('Cancelled auction releases PP without debit',()=>{run("UPDATE auctions SET status='cancelled' WHERE id='two'");assert.equal(q("SELECT reserved FROM members WHERE id='b'").reserved,180);assert.equal(q("SELECT balance FROM members WHERE id='b'").balance,1000);});
test('Open auction cannot settle early',()=>assert.throws(()=>run("UPDATE auctions SET status='closed' WHERE id='one'")));
test('Closed auction deducts PP once and releases reservation',()=>{run("UPDATE auctions SET ends=? WHERE id='one'",now-1);run("UPDATE auctions SET status='closed' WHERE id='one'");assert.equal(q("SELECT balance FROM members WHERE id='b'").balance,820);assert.equal(q("SELECT reserved FROM members WHERE id='b'").reserved,0);assert.equal(q("SELECT COUNT(*) n FROM ledger WHERE id='auction:one'").n,1);});
test('Repeated settlement cannot charge again',()=>{run("UPDATE auctions SET status='closed' WHERE id='one'");assert.equal(q("SELECT balance FROM members WHERE id='b'").balance,820);assert.throws(()=>run("UPDATE auctions SET status='active' WHERE id='one'"));});
test('Bidding on a closed auction is rejected',()=>assert.throws(()=>bid('closed','a',300)));
run("INSERT INTO deposits(id,member_id,yang,pp,kind,week,note,created) VALUES('d1','a',500000,20,'weekly','2026-10-05','',?)",now);
test('Pending deposit has no PP credit',()=>assert.equal(q("SELECT balance FROM members WHERE id='a'").balance,1000));
test('Weekly deposits cannot be duplicated',()=>assert.throws(()=>run("INSERT INTO deposits(id,member_id,yang,pp,kind,week,note,created) VALUES('d2','a',500000,20,'weekly','2026-10-05','',?)",now)));
test('Approval credits PP exactly once',()=>{run("UPDATE deposits SET status='approved',reviewed_by='b' WHERE id='d1'");assert.equal(q("SELECT balance FROM members WHERE id='a'").balance,1020);assert.throws(()=>run("UPDATE deposits SET status='approved',reviewed_by='b' WHERE id='d1'"));assert.equal(q("SELECT balance FROM members WHERE id='a'").balance,1020);});
run("INSERT INTO deposits(id,member_id,yang,pp,kind,note,created) VALUES('d3','a',1000000,40,'donation','',?)",now);
test('Rejection does not credit PP',()=>{run("UPDATE deposits SET status='rejected',reviewed_by='b' WHERE id='d3'");assert.equal(q("SELECT balance FROM members WHERE id='a'").balance,1020);});
run("INSERT INTO events(id,title,type,starts,pp,description,created_by,created) VALUES('e1','Demon Tower','PvE',?,80,'','a',?)",now-100,now);
run("INSERT INTO event_members(event_id,member_id,joined,attended,created) VALUES('e1','a',1,1,?)",now);run("INSERT INTO event_members(event_id,member_id,joined,created) VALUES('e1','b',1,?)",now);
test('RSVP alone gives no PP',()=>assert.equal(q("SELECT balance FROM members WHERE id='b'").balance,820));
run("UPDATE event_members SET attended=1 WHERE event_id='e1' AND member_id='b'");
test('Legacy event reward rules remain unchanged',()=>{run("UPDATE events SET status='completed' WHERE id='e1'");assert.equal(q("SELECT balance FROM members WHERE id='a'").balance,1020);assert.equal(q("SELECT balance FROM members WHERE id='b'").balance,900);});
test('Repeated event completion cannot duplicate rewards',()=>{run("UPDATE events SET status='completed' WHERE id='e1'");assert.equal(q("SELECT balance FROM members WHERE id='a'").balance,1020);});
test('Finalized attendance cannot be modified',()=>assert.throws(()=>run("UPDATE event_members SET attended=1 WHERE event_id='e1' AND member_id='b'")));
test('Ledger history is immutable',()=>{assert.throws(()=>run("DELETE FROM ledger WHERE id='seed:a'"));assert.throws(()=>run("UPDATE ledger SET amount=9000 WHERE id='seed:a'"));});
test('PP cannot be spent below other reservations',()=>{auction('three');bid('b7','a',1000,'three');assert.throws(()=>run("INSERT INTO ledger VALUES('bad-debit','a',-500,'Loot','bad',?)",now));assert.equal(q("SELECT balance FROM members WHERE id='a'").balance,1020);});
test('Rejected weekly deposits can be resubmitted',()=>{run("INSERT INTO deposits(id,member_id,yang,pp,kind,week,note,created) VALUES('rejected-week','c',500000,20,'weekly','2026-10-05','',?)",now);run("UPDATE deposits SET status='rejected',reviewed_by='a' WHERE id='rejected-week'");run("INSERT INTO deposits(id,member_id,yang,pp,kind,week,note,created) VALUES('replacement-week','c',500000,20,'weekly','2026-10-05','',?)",now);assert.equal(q("SELECT COUNT(*) n FROM deposits WHERE member_id='c' AND week='2026-10-05'").n,2);});
run("UPDATE members SET admin=1 WHERE id='b'");
run("INSERT INTO events(id,title,type,starts,pp,description,created_by,created,kind,phase,creation_day,duration_minutes,location) VALUES('help-guard','Help','PvE',?,10,'','a',?,'Help','open','2026-10-07',30,'Spider Dungeon 2')",now,now);
test('Help cannot end without screenshot evidence even through direct SQL',()=>assert.throws(()=>run("UPDATE events SET phase='confirming',ended=? WHERE id='help-guard'",now),/screenshot/));
test('Creator cannot sign up twice for an automatic reward',()=>assert.throws(()=>run("INSERT INTO event_members(event_id,member_id,joined,created) VALUES('help-guard','a',1,?)",now),/creator/i));
test('Help duration and location are immutable',()=>{assert.throws(()=>run("UPDATE events SET duration_minutes=90 WHERE id='help-guard'"));assert.throws(()=>run("UPDATE events SET location='Demon Tower' WHERE id='help-guard'"));});
run("INSERT INTO event_members(event_id,member_id,joined,created) VALUES('help-guard','b',1,?)",now);run("INSERT INTO event_members(event_id,member_id,joined,created) VALUES('help-guard','c',1,?)",now);
test('Screenshot upload is allowed before ending Help',()=>{run("INSERT INTO event_evidence(id,event_id,uploaded_by,filename,content_type,created) VALUES('proof-guard','help-guard','a','proof.png','image/png',?)",now);run("UPDATE events SET phase='confirming',ended=? WHERE id='help-guard'",now);});
run("UPDATE event_members SET attended=1 WHERE event_id='help-guard' AND member_id='b'");run("UPDATE events SET phase='pending',submitted=? WHERE id='help-guard'",now);
test('Unconfirmed members cannot be inserted into the reward review',()=>assert.throws(()=>run("INSERT INTO event_reward_reviews VALUES('help-guard','c','approved','b',?)",now),/eligible/));
for(const member of ['a','b'])run("INSERT INTO event_reward_reviews VALUES('help-guard',?,'approved','b',?)",member,now);
test('Help approval credits creator and confirmed participants, excluding unconfirmed members',()=>{const creatorBefore=q("SELECT balance FROM members WHERE id='a'").balance;const unconfirmedBefore=q("SELECT balance FROM members WHERE id='c'").balance;const before=q("SELECT balance FROM members WHERE id='b'").balance;run("UPDATE events SET phase='approved',status='completed',reviewed_by='b',reviewed=? WHERE id='help-guard'",now);assert.equal(q("SELECT balance FROM members WHERE id='b'").balance,before+10);assert.equal(q("SELECT balance FROM members WHERE id='a'").balance,creatorBefore+10);assert.equal(q("SELECT balance FROM members WHERE id='c'").balance,unconfirmedBefore);assert.equal(q("SELECT COUNT(*) n FROM ledger WHERE id LIKE 'event:help-guard:%'").n,2);run("UPDATE events SET status='completed' WHERE id='help-guard'");assert.equal(q("SELECT balance FROM members WHERE id='a'").balance,creatorBefore+10);});
test('Individual reward decisions are immutable',()=>{assert.throws(()=>run("UPDATE event_reward_reviews SET decision='rejected' WHERE event_id='help-guard'"));assert.throws(()=>run("DELETE FROM event_reward_reviews WHERE event_id='help-guard'"));});
console.log(`${checks} financial integrity checks passed`);
