import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:3092';
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,headless:true});
const boundary=Date.parse('2027-01-01T00:30:00Z')/1000;
const zones=[['Europe/Istanbul','JAN','01','03:30','2027-01-15T17:30:00Z'],['America/New_York','DEC','31','19:30','2027-01-16T01:30:00Z'],['Asia/Tokyo','JAN','01','09:30','2027-01-15T11:30:00Z'],['Europe/Paris','JAN','01','01:30','2027-01-15T19:30:00Z']];
try{for(const [zone,month,day,hour,utc] of zones){const context=await browser.newContext({timezoneId:zone,viewport:{width:390,height:900}}),page=await context.newPage();await page.goto(base);await page.getByRole('button',{name:'Try as Guild Leader',exact:true}).click();await page.getByRole('navigation').waitFor();
const result=await page.evaluate(async({starts})=>{const r=await fetch('/api/admin/event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),title:'Timezone Boundary',type:'PvE',starts,pp:10,description:''})});return r.status;},{starts:boundary});assert.equal(result,200);
await page.goto(base+'/?view=events');const row=page.locator('.pg-event-row').filter({has:page.getByRole('heading',{name:'Timezone Boundary',exact:true})});await row.waitFor();assert.equal(await row.locator('.pg-date-tile span').innerText(),month);assert.equal(await row.locator('.pg-date-tile strong').innerText(),day);assert.ok((await row.innerText()).includes(hour));assert.ok((await page.locator('.pg-footer').innerText()).includes(zone));assert.equal(await page.getByText('TRT / UTC+3',{exact:true}).count(),0);
await page.getByRole('button',{name:'Manage Events',exact:true}).click();await page.getByLabel('Event Name',{exact:true}).fill('Local Input Test');await page.getByLabel('Date & Time — '+zone,{exact:true}).fill('2027-01-15T20:30');await page.getByRole('button',{name:'Create Event',exact:true}).click();await page.getByText('Guild event announced.',{exact:true}).waitFor();const state=await (await context.request.get(base+'/api/state')).json();assert.equal(state.events.find(e=>e.title==='Local Input Test').starts,Date.parse(utc)/1000);
// Summer and winter conversion checks catch hardcoded offsets in the input parser.
const seasonal=await page.evaluate(()=>[new Date('2027-01-15T20:30').toISOString(),new Date('2027-07-15T20:30').toISOString()]);if(zone==='America/New_York')assert.deepEqual(seasonal,['2027-01-16T01:30:00.000Z','2027-07-16T00:30:00.000Z']);if(zone==='Europe/Paris')assert.deepEqual(seasonal,['2027-01-15T19:30:00.000Z','2027-07-15T18:30:00.000Z']);if(zone==='Europe/Paris'){await page.getByLabel('Event Name',{exact:true}).fill('DST Gap Test');await page.getByLabel('Date & Time — '+zone,{exact:true}).fill('2027-03-28T02:30');await page.getByRole('button',{name:'Create Event',exact:true}).click();await page.getByRole('alert').getByText('That local time does not exist in your time zone. Choose another time.',{exact:true}).waitFor();const after=await (await context.request.get(base+'/api/state')).json();assert.equal(after.events.some(e=>e.title==='DST Gap Test'),false);}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await context.close();console.log('PASS '+zone+': local date boundary, display zone, local event input saved as UTC, seasonal offsets.');}
}finally{await browser.close();}
for(const [zone,,,hour] of zones){const handlers={},notifications=[];const context={Intl:{DateTimeFormat:function(locale,opts){return new Intl.DateTimeFormat(locale,{...opts,timeZone:zone});}},Date,URL,Number,self:{addEventListener:(type,fn)=>handlers[type]=fn,registration:{showNotification:async(title,data)=>notifications.push({title,...data})}}};vm.runInNewContext(readFileSync(new URL('../public/sw.js',import.meta.url),'utf8'),context);let pending;handlers.push({data:{json:()=>({title:'Paragon — Event Reminder',body:'UTC fallback',eventTitle:'Timezone Boundary',eventStarts:boundary})},waitUntil:p=>pending=p});await pending;assert.ok(notifications[0].body.includes(hour));assert.equal(notifications[0].data.url,'/?view=events');}console.log('PASS notification formatting follows each device zone.');
