import type {Metadata} from 'next';
import type {ReactNode} from 'react';
import GuildFooter from '../guild-footer';
import GuideNavigation from './guide-navigation';
import './guide.css';
export const metadata:Metadata={title:'How to Use — Paragon',description:'A short visual guide to Paragon: iPhone setup, notifications, events, PP and auctions.'};
export const dynamic='force-static';
const topics=[['phone','Add to iPhone','Open from your Home Screen'],['notifications','Turn on notifications','New events & reminders'],['events','Join an event','Sign up, attend, earn PP'],['help','Create & finish an event','Request help, upload proof, confirm attendance'],['auctions','Place a bid','Use PP to win guild loot'],['points','Check your PP & deposits','Your balance & weekly contribution'],['administrators','Admin controls','Approve rewards, adjust PP, start auctions']] as const;
function Steps({children}:{children:ReactNode}){return <ol className="pg-guide-steps">{children}</ol>;}
function Step({title,children}:{title:string;children?:ReactNode}){return <li><strong>{title}</strong>{children&&<p>{children}</p>}</li>;}
function Screen({name,alt,width,height}:{name:string;alt:string;width:number;height:number}){return <figure className="pg-guide-screen"><a href={'/guide/'+name+'.png'} target="_blank" rel="noopener noreferrer" aria-label={'Enlarge: '+alt+' (opens in a new tab)'}><img src={'/guide/'+name+'.png'} width={width*2} height={height*2} alt={alt} loading={name==='home'?'eager':'lazy'} fetchPriority={name==='home'?'high':undefined} decoding="async"/></a><figcaption>Example screen · Tap to enlarge</figcaption></figure>;}
function Flow({children,screen}:{children:ReactNode;screen:ReactNode}){return <div className="pg-guide-flow"><div className="pg-guide-instructions">{children}</div>{screen}</div>;}
function Note({children}:{children:ReactNode}){return <p className="pg-guide-note">{children}</p>;}
function Topic({index,children}:{index:number;children:ReactNode}){const [id,title,subtitle]=topics[index];return <details className="pg-guide-topic" id={id} name="paragon-guide" open={index===0}><summary><span className="pg-guide-number">{String(index+1).padStart(2,'0')}</span><span><h2>{title}</h2><span className="pg-guide-subtitle">{subtitle}</span></span><span className="pg-guide-toggle" aria-hidden="true"/></summary><div className="pg-guide-body">{children}</div></details>;}
export default function HowToUse(){return <div id="paragon-design"><div className="pg-stage"><div className="pg-app pg-guide-app">
<a className="pg-skip" href="#main-content">Skip to content</a>
<header className="pg-masthead"><a className="pg-brand pg-guide-brand" href="/" aria-label="Paragon home"><img className="pg-crest" src="/branding/paragon-emblem.png" width={80} height={80} alt=""/><div><strong className="pg-guide-brand-name" translate="no">PARAGON</strong><span>ARTHION GUILD</span></div></a><a className="pg-button" href="/">Open Paragon</a></header>
<main className="pg-guide-main" id="main-content">
<header className="pg-guide-heading"><h1>How to Use</h1><p>Choose a topic. Follow the steps.</p><div className="pg-guide-entry"><b>First visit?</b> Open Paragon → <b>Sign in with Discord</b>. Your account needs the guild’s Member role.</div></header>
<GuideNavigation topics={topics.map(([id,title])=>({id,title}))}/><p className="pg-guide-examples">Real app screens with sample accounts.</p>
<Topic index={0}><Flow screen={<Screen name="home" width={390} height={620} alt="Paragon on a phone with Weekly Quests and the four bottom navigation buttons"/>}>
<Steps><Step title="Open paragonguild.xyz in Safari">If the link opened inside Discord, open it in Safari.</Step><Step title="Share → Add to Home Screen">Tap <b>Add</b>. Keep <b>Open as Web App</b> on if shown.</Step><Step title="Open the Paragon icon">Launch it from your iPhone Home Screen, then sign in.</Step></Steps>
<Note>For iPhone notifications, use the Home Screen app on iOS 16.4 or later.</Note><a className="pg-guide-source" href="https://support.apple.com/guide/iphone/open-as-web-app-iphea86e5236/ios" target="_blank" rel="noopener noreferrer">Apple’s illustrated instructions ↗</a><p className="pg-guide-small">Use the bottom bar for Home, Auctions, Events and Profile.</p>
</Flow></Topic>
<Topic index={1}><Flow screen={<Screen name="notifications" width={358} height={413} alt="Profile notification settings with the new-event checkbox and Enable Device Notifications button"/>}>
<Steps><Step title="Profile → Notifications & App Settings"/><Step title="Enable Device Notifications → Allow">Accept the permission on your phone.</Step><Step title="Keep new-event alerts checked">Receive an alert when an event is announced.</Step><Step title="Tap Test Device Notification">This button appears after enabling notifications. Check your Lock Screen or notification centre.</Step></Steps><Note>On iPhone, do this inside the installed Paragon app. Enable notifications on each device.</Note>
</Flow><Flow screen={<Screen name="reminder" width={358} height={354} alt="Event Reminder dialog with a Remind Me time selector and Save Reminder button"/>}>
<h3>Want a reminder?</h3><Steps><Step title="Open an upcoming event → Remind Me"/><Step title="Choose 15, 30 or 60 minutes before"/><Step title="Tap Save Reminder">Tap the alert when it arrives to open the event.</Step></Steps><p className="pg-guide-small">Help starts now, so use new-event alerts for Help requests.</p>
</Flow><Note>No alert? Check <b>Settings → Notifications → Paragon</b>, allow notifications and check Focus / Do Not Disturb. Try the test again. Signing out stops push on that device.</Note></Topic>
<Topic index={2}><Flow screen={<Screen name="join-event" width={358} height={742} alt="Help event details with the map, CH-3, 10 PP reward and Join Event button"/>}>
<Steps><Step title="Events → Open an event">Check the map, channel and start time. Times follow your device.</Step><Step title="Tap Join Event">Your name appears in Participants. Use <b>Leave Event</b> if you cannot attend.</Step><Step title="Attend in game">The host confirms attendance and uploads proof.</Step><Step title="Receive PP after admin approval">Check <b>Profile</b>. Signing up alone does not earn points.</Step></Steps>
<dl className="pg-guide-rewards"><div><dt>Help</dt><dd>10 PP</dd></div><div><dt>Demon Tower</dt><dd>10 PP</dd></div><div><dt>PvE</dt><dd>35 PP</dd></div><div><dt>Open PvP / Guild War</dt><dd>100 PP</dd></div><div><dt>World Boss</dt><dd>75 PP</dd></div><div><dt>Custom</dt><dd>Chosen by host</dd></div></dl><p className="pg-guide-small">The creator and approved participants receive the same reward.</p>
</Flow></Topic>
<Topic index={3}><Flow screen={<Screen name="create-help" width={358} height={853} alt="Help creation form at Spider Dungeon 2, CH-3, lasting 60 minutes"/>}>
<h3>1. Create</h3><Steps><Step title="Events → Create Event → Help"/><Step title="Enter the name, map & channel">Choose CH-1 to CH-6 and a duration in minutes.</Step><Step title="Tap Start Help Event">Help starts immediately. You can create two Help events per guild day.</Step></Steps><Note>Every type except Help requires the Experienced role. Choose a start time; finish manually with End Event.</Note>
</Flow><Flow screen={<Screen name="custom-event" width={358} height={983} alt="Custom event creation with a title, CH-6, Guild courtyard location, 41 PP and a start time"/>}><h3>Experienced: custom events</h3><Steps><Step title="Create Event → Custom"/><Step title="Set the title, location, channel & PP">Choose a map, or <b>Custom…</b> and enter a meeting point.</Step><Step title="Choose the start time → Schedule Event">There is no end time. Open the event and tap <b>End Event</b> when finished.</Step></Steps><Note>Demon Tower is a separate 10 PP type with its map already selected. All event rewards still require proof and admin approval.</Note></Flow><Flow screen={<Screen name="evidence" width={324} height={453} alt="Screenshot Evidence section with an example image and Upload Screenshot control"/>}>
<h3>2. Upload proof & end</h3><Steps><Step title="Open your event → Screenshot Evidence"/><Step title="Choose your screenshot → Upload Screenshot">PNG, JPEG or WebP; under 8 MB. Up to three screenshots.</Step><Step title="Tap End Event">Help cannot end without a screenshot. Its duration does not finish the event automatically.</Step></Steps>
</Flow><Flow screen={<Screen name="attendance" width={358} height={755} alt="Attendance confirmation with a selected participant, the creator and Submit for Approval below"/>}>
<h3>3. Confirm & submit</h3><Steps><Step title="Select the people who attended">Use <b>Select All</b>, then uncheck anyone who did not attend.</Step><Step title="Tap Submit for Approval">Your selections are sent together. Proof is required for every event type.</Step><Step title="Wait for admin review">The creator and approved participants earn the event’s PP.</Step></Steps><p className="pg-guide-small">Find your events in <b>My Events</b> or <b>Profile</b>. To cancel: <b>Cancel This Event → Confirm Cancellation</b>. No PP is awarded.</p>
</Flow></Topic>
<Topic index={4}><Flow screen={<Screen name="bid" width={358} height={394} alt="Place a Bid dialog showing the minimum next bid, total bid input and Confirm Bid button"/>}>
<Steps><Step title="Auctions → Choose an item">Check the screenshot, highest bidder, bid history and time left.</Step><Step title="Place Bid → Enter your total bid">Follow the minimum and increment. To raise 40 to 60 PP, enter <b>60</b>.</Step><Step title="Tap Confirm Bid">A leading bid reserves PP. If someone outbids you, it is released.</Step><Step title="Check Auction History">Only the winner pays, once the auction is finalized.</Step></Steps><Note><b>100 PP balance + 40 PP leading bid</b><br/>100 balance · 40 reserved · 60 available.<br/>Win at 40? Your balance becomes 60 PP.</Note>
</Flow></Topic>
<Topic index={5}><Flow screen={<Screen name="weekly-quest" width={358} height={340} alt="Weekly Guild Bank Contribution marked Completed after 500,000 Yang is recorded"/>}>
<h3>Weekly contribution</h3><Steps><Step title="Give 500,000 Yang in game">To <b>GuildBanker</b> at the <b>CH-3 Blacksmith</b>.</Step><Step title="Wait for the Deposit Log entry">The site checks every five minutes. No manual submission.</Step><Step title="Home shows Completed">Receive <b>20 PP</b> once for that week. The guild week resets every Monday in Istanbul time.</Step></Steps>
</Flow><Flow screen={<Screen name="points" width={358} height={554} alt="Profile PP summary with balance, available and reserved amounts above transaction history"/>}>
<h3>Your profile</h3><Steps><Step title="Profile → Your Participation Points">See your balance and every reward or deduction.</Step><Step title="Check Available before bidding">Available = balance minus PP reserved for leading bids.</Step><Step title="Check Guild Bank Contributions">See total Yang, this week’s amount and <b>Deposit History</b>, highest amounts first. Your event history is here too.</Step></Steps><p className="pg-guide-small">Historical deposits earn 20 PP per 500,000 Yang, rounded down to whole PP. Missing a payment? Ask an admin to check your character name in the log.</p>
</Flow></Topic>
<Topic index={6}><p className="pg-guide-small">These controls appear for administrators only.</p><Flow screen={<Screen name="review" width={358} height={860} alt="Admin event review with separate creator and participant checkboxes and Approve Selected"/>}>
<h3>Approve event rewards</h3><Steps><Step title="Events → Review → Open the event">Check the screenshot evidence.</Step><Step title="Choose Reward Recipients">Uncheck anyone who should receive no PP, including the creator.</Step><Step title="Tap Approve Selected">To reject the whole event, give a reason and use <b>Reject Event</b>.</Step></Steps>
</Flow><Flow screen={<Screen name="admin-points" width={324} height={609} alt="Admin PP adjustment form with selected player, action, amount and reason"/>}>
<h3>Add or remove PP</h3><Steps><Step title="Account menu → Admin Panel"/><Step title="Find & select the player">Choose <b>Add PP</b> or <b>Remove PP</b>.</Step><Step title="Enter the amount & reason → Save">Removing points also needs <b>Confirm Removal</b>. Reserved auction PP cannot be spent.</Step></Steps>
</Flow><Flow screen={<Screen name="create-auction" width={356} height={708} alt="Admin auction form with item screenshot, name and bidding settings"/>}>
<h3>Start an auction</h3><Steps><Step title="Auctions → Manage Auctions"/><Step title="Upload the item screenshot & enter its name">Set the minimum bid, increment and duration.</Step><Step title="Tap Start Auction">Cancelling an auction releases the leading bidder’s reserved PP.</Step></Steps>
</Flow></Topic>
<div className="pg-guide-help"><b>Cannot sign in?</b> Check your Discord Member role. If Discord is temporarily unavailable, wait briefly and try again.</div>
</main><GuildFooter standalone guide/></div></div></div>;}
