'use client';
import {useLanguage} from '@/app/language-provider';
import {t,localeTag,translate} from '@/lib/i18n';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {localTime} from '@/lib/local-time';
type Player={id:string;name:string;class:string;balance:number;reserved:number};
type Award={id:string;member_id:string;name:string;amount:number;label:string;created:number;awarded_by:string};
const fmt=(n:number)=>new Intl.NumberFormat(localeTag()).format(n);
export default function AdminPoints({onChange}:{onChange:()=>Promise<void>}){
 useLanguage();
 const [players,setPlayers]=useState<Player[]>([]),[awards,setAwards]=useState<Award[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[operation,setOperation]=useState<'add'|'remove'>('add'),[review,setReview]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(false);
 const form=useRef<HTMLFormElement>(null),draft=useRef<{signature:string;id:string}|null>(null);
 async function read(){const r=await fetch('/api/admin/players',{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw new Error(j.error);setPlayers(j.players);setAwards(j.awards);}
 useEffect(()=>{let live=true;read().catch(e=>{if(live){setMessage(e.message);setError(true);}}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 const player=players.find(p=>p.id===selected),visible=players.filter(p=>(p.name+' '+p.class+' '+t(p.class)).toLocaleLowerCase(localeTag()).includes(query.toLocaleLowerCase(localeTag()).trim()));
 async function grant(ev:FormEvent<HTMLFormElement>){ev.preventDefault();if(busy||!player)return;const f=new FormData(ev.currentTarget),payload={memberId:player.id,operation,amount:Number(f.get('amount')),note:String(f.get('note')).trim()},signature=JSON.stringify(payload);if(operation==='remove'&&review!==signature){setReview(signature);return;}if(draft.current?.signature!==signature)draft.current={signature,id:crypto.randomUUID()};setBusy(true);setError(false);setMessage('');let saved=false;
  try{const r=await fetch('/api/admin/points',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,id:draft.current!.id})});const j:any=await r.json();if(!r.ok)throw new Error(j.error);saved=true;draft.current=null;setReview('');form.current?.reset();setMessage(translate(operation==='remove'?'{amount} PP removed from {name}.':'{amount} PP added to {name}.','en',{amount:fmt(payload.amount),name:player.name}));await Promise.all([read(),onChange()]);}
  catch(e){setMessage(saved?'PP updated. Refresh to see the updated balance.':e instanceof Error?e.message:'Please try again.');setError(!saved);}finally{setBusy(false);}
 }
 return <div className="pg-admin-points"><section className="pg-window" aria-labelledby="pg-grant-title"><div className="pg-title"><h3 id="pg-grant-title">{t("Adjust Participation Points")}</h3></div>{message&&<p className={'pg-message'+(error?' pg-error':'')} role={error?'alert':'status'}>{t(message)}</p>}
 <div className="pg-grant-layout"><div className="pg-player-picker"><label className="pg-field"><span>{t("Find a Player")}</span><input name="playerSearch" type="search" value={query} onChange={e=>setQuery(e.target.value)} autoComplete="off" placeholder={t("Search name or class…")}/></label><span className="pg-dim">{loading?t('Loading players…'):t('{count} players',{count:visible.length})}</span><ul className="pg-grant-players" aria-label={t("Guild players")}>{visible.map(p=><li key={p.id}><label className="pg-grant-player"><input type="radio" name="grantPlayer" value={p.id} checked={selected===p.id} disabled={busy} onChange={()=>{setSelected(p.id);setReview('');}}/><span><strong>{p.name}</strong><small>{t(p.class)}</small></span><b>{fmt(p.balance)} <small>PP</small></b></label></li>)}</ul>{!loading&&!visible.length&&<p className="pg-empty">{t("No players match your search.")}</p>}</div>
 <form ref={form} className="pg-form pg-grant-form" onSubmit={grant} onChange={()=>setReview('')}><div className="pg-grant-recipient"><span className="pg-dim">{t("Selected Player")}</span><strong>{player?.name||t("Choose a player")}</strong>{player&&<span>{t(player.class)} · {fmt(player.balance)} PP</span>}{player&&<span>{fmt(player.balance-player.reserved)}{t(" PP available")}{player.reserved>0?' · '+fmt(player.reserved)+t(" reserved for auctions"):''}</span>}</div><label className="pg-field"><span id="pg-points-action">{t("Action")}</span><select aria-labelledby="pg-points-action" name="operation" value={operation} disabled={busy} onChange={e=>setOperation(e.target.value as 'add'|'remove')}><option value="add">{t("Add PP")}</option><option value="remove">{t("Remove PP")}</option></select></label><label className="pg-field"><span>{t("PP Amount")}</span><input name="amount" type="number" inputMode="numeric" min={1} max={operation==='remove'&&player?Math.min(1000000,player.balance-player.reserved):1000000} step={1} required autoComplete="off" disabled={busy} placeholder="25"/></label><label className="pg-field"><span>{t("Reason")}</span><textarea name="note" rows={3} required maxLength={300} autoComplete="off" disabled={busy} placeholder={t("Reason for this PP adjustment…")}/></label>{review&&operation==='remove'&&player&&<p className="pg-adjustment-confirm" role="alert">{t('Confirm removing {amount} PP from {name}?',{amount:fmt(JSON.parse(review).amount),name:player.name})} {t('Balance: {before} → {after} PP.',{before:fmt(player.balance),after:fmt(player.balance-JSON.parse(review).amount)})}</p>}<button className="pg-button pg-red" type="submit" disabled={busy||!player||(operation==='remove'&&player.balance<=player.reserved)}>{busy?t("Saving…"):operation==='remove'?(review?t("Confirm Removal"):t("Remove PP")):t("Add PP")}</button>{review&&<button className="pg-button" type="button" disabled={busy} onClick={()=>setReview('')}>{t("Cancel")}</button>}<p className="pg-dim">{t("Recorded in the player’s PP history with the administrator and reason.")}</p></form></div></section>
 <section className="pg-window" aria-labelledby="pg-recent-awards"><div className="pg-title"><h3 id="pg-recent-awards">{t("Recent PP Adjustments")}</h3></div>{awards.length?<ul className="pg-manual-awards">{awards.map(a=><li key={a.id}><div><strong>{a.name}</strong><p>{a.label}</p><small>{localTime(a.created)} · {a.awarded_by}</small></div><b className={a.amount<0?'pg-negative':undefined}>{a.amount>0?'+':''}{fmt(a.amount)} PP</b></li>)}</ul>:<p className="pg-empty">{t("No manual adjustments yet.")}</p>}</section></div>;
}
