'use client';
import {useLanguage} from '@/app/language-provider';
import {t,localeTag} from '@/lib/i18n';
import {useMemo,useState} from 'react';
import {CLASSES} from '@/lib/domain';
type GuildMember={id:string;name:string;class:string;total_yang?:number};
const PAGE_SIZE=10;
export default function GuildRoster({members,currentId}:{members:GuildMember[];currentId:string}){
 useLanguage();
 const [search,setSearch]=useState(''),[classFilter,setClassFilter]=useState('All'),[page,setPage]=useState(0);
 const filtered=useMemo(()=>members.filter(m=>(classFilter==='All'||m.class===classFilter)&&m.name.toLocaleLowerCase('en-GB').includes(search.trim().toLocaleLowerCase('en-GB'))).sort((a,b)=>(b.total_yang??0)-(a.total_yang??0)||a.name.localeCompare(b.name,'en-GB',{numeric:true,sensitivity:'base'})),[members,search,classFilter]);
 const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),currentPage=Math.min(page,pages-1),start=currentPage*PAGE_SIZE,visible=filtered.slice(start,start+PAGE_SIZE);
 return <div className="pg-roster"><div className="pg-roster-tools"><label className="pg-field"><span>{t("Find a Member")}</span><input name="memberSearch" type="search" placeholder={t("Character name…")} value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} autoComplete="off" spellCheck={false}/></label><label className="pg-field"><span>{t("Class")}</span><select aria-label={t("Class")} name="memberClass" value={classFilter} onChange={e=>{setClassFilter(e.target.value);setPage(0);}}><option value="All">{t("All Classes")}</option>{CLASSES.map(c=><option key={c} value={c}>{t(c)} ({members.filter(m=>m.class===c).length})</option>)}</select></label></div><div className="pg-roster-header" aria-hidden="true"><span>{t("Character")}</span><span>{t("Class")}</span></div><ul className="pg-roster-list" aria-label={t("Guild members")}>{visible.map(m=><li className="pg-roster-row" key={m.id}><div className="pg-roster-person"><div className="pg-roster-portrait" aria-hidden="true"><img src={['Warrior','Ninja','Shaman','Sura'].includes(m.class)?'/metin2/'+m.class.toLowerCase()+'.png':'/icon-192.png'} width={32} height={42} alt="" loading="lazy"/></div><div className="pg-roster-name">{m.name}{m.total_yang!==undefined&&<span className="pg-roster-paid">{m.total_yang.toLocaleString(localeTag())}{t(" Yang deposited")}</span>}{m.id===currentId&&<span className="pg-roster-you">{t("You")}</span>}</div></div><span className="pg-roster-class">{t(m.class)}</span></li>)}</ul>{!visible.length&&<p className="pg-empty">{members.length?t("No members match your search."):t("No guild members yet.")}</p>}<div className="pg-roster-pagination"><span aria-live="polite">{filtered.length?t('{current}–{end} of {total}',{current:start+1,end:Math.min(start+PAGE_SIZE,filtered.length),total:filtered.length}):t("0 Members")}{filtered.length!==members.length&&' / '+t('{count} total',{count:members.length})}</span><div className="pg-roster-page-actions"><button type="button" className="pg-button" aria-label={t("Previous members page")} disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>{t("Previous")}</button><span>{currentPage+1} / {pages}</span><button type="button" className="pg-button" aria-label={t("Next members page")} disabled={currentPage===pages-1} onClick={()=>setPage(currentPage+1)}>{t("Next")}</button></div></div></div>;
}
