'use client';
import {useState} from 'react';
import {EventSummary} from './guild-events';
import {ContributionStatus} from './guild-contributions';
import type {GuildData} from '@/lib/domain';
import {localTime} from '@/lib/local-time';
export default function GuildHome({data,onChange}:{data:GuildData;onChange:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
 const source=data.contribution;const quest=data.deposits.find(d=>d.kind==='weekly'&&d.week===data.week&&d.status!=='rejected');const completed=source?Boolean(source.checked)&&source.weekly_yang>=data.settings.weekly:quest?.status==='approved',status=source?(!source.checked?'Syncing':completed?'Completed':'Not Completed'):completed?'Completed':quest?'Awaiting Approval':'Not Completed';
 const current=data.events.filter(e=>e.phase==='open'||e.kind==='Legacy'&&e.status==='upcoming');
 const auctions=data.auctions.filter(a=>a.status==='active'&&a.ends>Date.now()/1000);
 async function submit(){if(busy)return;setBusy(true);setError(false);try{const r=await fetch('/api/deposit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),kind:'weekly',yang:data.settings.weekly,note:'Weekly Quest · Ch-3 Blacksmith · GuildBanker'})});const j:any=await r.json();if(!r.ok)throw new Error(j.error);await onChange();setMessage('Transfer submitted for administrator approval.');}catch(e){setMessage(e instanceof Error?e.message:'Please try again.');setError(true);}finally{setBusy(false);}}
 return <div className="pg-home"><section className={'pg-window pg-weekly-quest'+(completed?' pg-quest-completed':'')}><div className="pg-title"><h3>Weekly Quests</h3><span className={completed?'pg-green':'pg-dim'}>{status}</span></div><div className="pg-quest-body"><div><h4>Guild Bank Contribution</h4><p>Give {new Intl.NumberFormat('en-GB').format(data.settings.weekly)} Yang to <strong>GuildBanker</strong> at the <strong>Ch-3 Blacksmith</strong>.</p><span>{data.settings.rate} PP {source?'after the transfer appears in the Deposit Log':'after administrator approval'} · Resets every Monday</span></div>{source?<div className="pg-quest-progress"><strong className={completed?'pg-green':'pg-dim'}>{completed?'Quest Completed':source.checked?new Intl.NumberFormat('en-GB').format(source.weekly_yang)+' / '+new Intl.NumberFormat('en-GB').format(data.settings.weekly)+' Yang':'Checking Deposit Log…'}</strong><progress max={data.settings.weekly} value={Math.min(source.weekly_yang,data.settings.weekly)} aria-label="Weekly contribution progress"/></div>:quest?<strong className={quest.status==='approved'?'pg-green':'pg-gold'}>{quest.status==='approved'?'Quest Completed':'Transfer Submitted'}</strong>:<details className="pg-quest-confirm"><summary className="pg-button pg-red">I Have Given the Yang</summary><p>Confirm that you made the transfer in game. An administrator will verify it.</p><button className="pg-button" disabled={busy} onClick={()=>void submit()}>Confirm Yang Transfer</button></details>}</div>{source&&<ContributionStatus data={data}/>} {message&&<p className={'pg-message'+(error?' pg-error':'')} role={error?'alert':'status'}>{message}</p>}</section>
 <section className="pg-window"><div className="pg-title"><h3>Ongoing & Upcoming Events</h3><a className="pg-text-link" href="/?view=events">View All Events</a></div><EventSummary events={current.slice(0,5)}/><div className="pg-home-foot"><a className="pg-button" href="/?view=events&create=1">Create Event</a></div></section>
 <section className="pg-window"><div className="pg-title"><h3>Ongoing & Upcoming Auctions</h3><a className="pg-text-link" href="/?view=auctions">View All Auctions</a></div>{auctions.length?<ul className="pg-home-auctions">{auctions.slice(0,4).map(a=><li key={a.id}><a href={'/?view=auctions&auction='+a.id}><img className={a.icon.startsWith('/api/images/')?'pg-home-screenshot':undefined} src={a.icon} width={32} height={64} alt="" loading="lazy"/><div><strong>{a.name}{a.height===2?'+'+a.upgrade:''}</strong><span>{a.starts>Date.now()/1000?'Starts':'Ends'} {localTime(a.starts>Date.now()/1000?a.starts:a.ends)}</span><span>{a.winner_name?'Highest bidder: '+a.winner_name:'No bids yet'}</span></div><b>{a.current||a.minimum} PP</b></a></li>)}</ul>:<p className="pg-empty">No ongoing or upcoming auctions.</p>}</section></div>;
}
