'use client';
import {EventMapPicker,EventMapView} from './event-map';
import {eventMapPin,type MapPin} from '@/lib/event-maps';
import {useLanguage} from '@/app/language-provider';
import {t,localeTag} from '@/lib/i18n';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {localTime,localTimeZone,localInputTimestamp} from '@/lib/local-time';
import type {GuildData,Event} from '@/lib/domain';
import {EVENT_LOCATIONS,mapLabel} from '@/lib/event-locations';
import {EVENT_KINDS,EVENT_REWARDS,MAX_EVENT_PP,eventKindLabel,type EventKind} from '@/lib/event-types';
const typeLabel=(e:Event)=>eventKindLabel(e.kind==='Legacy'?e.type:e.kind);
export function eventLabel(e:Event){if(e.kind==='Legacy')return e.status==='upcoming'?(e.starts>Date.now()/1000?'Upcoming':'Ongoing'):e.status;return ({open:e.kind==='Help'&&e.duration_minutes&&e.starts+e.duration_minutes*60<=Date.now()/1000?'Awaiting Completion':e.starts>Date.now()/1000?'Upcoming':'Ongoing',confirming:'Confirming Attendance',pending:'Awaiting Approval',approved:'Approved',rejected:'Rejected',cancelled:'Cancelled'} as Record<string,string>)[e.phase]||e.phase;}
function eventTime(e:Event){return localTime(e.starts)+(e.kind==='Help'&&e.duration_minutes?' · '+e.duration_minutes+' '+t('min'):'');}
const eventPlace=(e:Event)=>[e.location?mapLabel(e.location):'',e.game_channel?'CH-'+e.game_channel:''].filter(Boolean).join(' · ');
export function EventSummary({events,empty='No ongoing or upcoming events.'}:{events:Event[];empty?:string}){
 useLanguage();return events.length?<ul className="pg-event-summary">{events.map(e=><li key={e.id}><a href={'/?view=events&event='+e.id}><div><strong>{e.title}</strong><span>{t(typeLabel(e))} · {eventTime(e)}</span>{(e.location||e.game_channel)&&<span>{eventPlace(e)}</span>}<span>{t("Hosted by ")}{e.creator_name}</span></div><div><b>{e.pp} PP</b><span>{t(eventLabel(e))}</span></div></a></li>)}</ul>:<p className="pg-empty">{t(empty)}</p>;}
type Detail={event:Event;participants:{member_id:string;name:string;class:string;joined:number;attended:number}[];reward_reviews:{member_id:string;decision:string}[];evidence:{id:string;created:number}[]};
export default function GuildEvents({data,onChange,manage=false,onReminder}:{data:GuildData;onChange:()=>Promise<void>;manage?:boolean;onReminder:(event:Event)=>void}){
 useLanguage();
 const [section,setSection]=useState(manage?'review':'schedule'),[limit,setLimit]=useState(50),[create,setCreate]=useState(false),[kind,setKind]=useState<EventKind>('Help'),[customPP,setCustomPP]=useState('10'),[customLocation,setCustomLocation]=useState(false),[filter,setFilter]=useState('All'),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<Detail|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
 const [mapLocation,setMapLocation]=useState(''),[mapPin,setMapPin]=useState<MapPin|null>(null);
 const reward=kind==='Custom'?Number(customPP):EVENT_REWARDS[kind];
 const [attendedIds,setAttendedIds]=useState<string[]>([]);
 const [approvedIds,setApprovedIds]=useState<string[]>([]);
 const approvalDraft=useRef<{eventId:string;dirty:boolean;ids:string[]}>({eventId:'',dirty:false,ids:[]}),reviewNote=useRef<HTMLTextAreaElement>(null);
 const attendanceDraft=useRef<{eventId:string;dirty:boolean;ids:string[]}>({eventId:'',dirty:false,ids:[]});
 const dialog=useRef<HTMLDialogElement>(null),createDialog=useRef<HTMLDialogElement>(null),requestId=useRef(crypto.randomUUID()),createForm=useRef<HTMLFormElement>(null);
 useEffect(()=>{const eventId=new URLSearchParams(location.search).get('event');if(eventId)setSelected(eventId);const params=new URLSearchParams(location.search);if(params.get('create')==='1'&&!eventId)setCreate(true);if(['mine','history'].includes(params.get('section')||''))setSection(params.get('section')!);if(params.get('manage')==='1'&&data.member.admin)setSection('review');if(EVENT_KINDS.some(k=>k===params.get('type')))setFilter(params.get('type')!);},[]);
 useEffect(()=>{if(create)createDialog.current?.showModal();else createDialog.current?.close();},[create]);
 useEffect(()=>{if(section==='review'&&!data.member.admin)setSection('schedule');},[data.member.admin,section]);
 function updateQuery(values:Record<string,string|null>){const url=new URL(location.href);for(const [key,value] of Object.entries(values)){if(value===null)url.searchParams.delete(key);else url.searchParams.set(key,value);}history.replaceState(null,'',url.pathname+url.search);}
 function changeSection(value:string){setSection(value);setLimit(50);setMessage('');updateQuery({section:value==='schedule'?null:value,manage:value==='review'?'1':null});}
 function openCreate(){if(busy)return;setMessage('');setError(false);setCreate(true);updateQuery({create:'1',event:null});}
 function closeCreate(){if(busy)return;setCreate(false);updateQuery({create:null});}
 async function readDetail(eventId:string,signal?:AbortSignal){const r=await fetch('/api/events/detail?id='+eventId,{cache:'no-store',signal});const j:any=await r.json();if(!r.ok)throw new Error(j.error);setDetail(j);const eligible=[j.event.created_by,...j.participants.filter((p:Detail['participants'][number])=>p.attended).map((p:Detail['participants'][number])=>p.member_id)];if(approvalDraft.current.eventId!==eventId||!approvalDraft.current.dirty||j.event.phase!=='pending'){approvalDraft.current={eventId,dirty:false,ids:eligible};setApprovedIds(eligible);}else{const ids=approvalDraft.current.ids.filter(id=>eligible.includes(id));approvalDraft.current.ids=ids;setApprovedIds(ids);}if(attendanceDraft.current.eventId!==eventId||!attendanceDraft.current.dirty||j.event.phase!=='confirming'){const ids=j.participants.filter((p:Detail['participants'][number])=>p.attended).map((p:Detail['participants'][number])=>p.member_id);attendanceDraft.current={eventId,dirty:false,ids};setAttendedIds(ids);}else{const allowed=new Set(j.participants.map((p:Detail['participants'][number])=>p.member_id));const ids=attendanceDraft.current.ids.filter(id=>allowed.has(id));attendanceDraft.current.ids=ids;setAttendedIds(ids);}}
 useEffect(()=>{if(!selected){setDetail(null);dialog.current?.close();return;}dialog.current?.showModal();const controller=new AbortController();readDetail(selected,controller.signal).catch(e=>{if(e.name!=='AbortError'){setMessage(e.message);setError(true);}});return()=>controller.abort();},[selected]);
 const eventVersion=data.events.find(e=>e.id===selected);
 useEffect(()=>{if(selected)readDetail(selected).catch(()=>{});},[eventVersion?.phase,eventVersion?.signups]);
 function chooseAttendance(ids:string[]){attendanceDraft.current={eventId:selected!,dirty:true,ids};setAttendedIds(ids);}
 useEffect(()=>{if(!attendanceDraft.current.dirty&&!approvalDraft.current.dirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[attendedIds,approvedIds]);
 function open(eventId:string){setMessage('');setError(false);setDetail(null);setSelected(eventId);const url=new URL(location.href);url.searchParams.set('event',eventId);history.replaceState(null,'',url.pathname+url.search);}
 function close(){if(busy)return;setSelected(null);const url=new URL(location.href);url.searchParams.delete('event');history.replaceState(null,'',url.pathname+url.search);}
 async function post(path:string,value:unknown){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const j:any=await r.json();if(!r.ok)throw new Error(j.error);}
 async function work(fn:()=>Promise<void>,success:string){if(busy)return;setBusy(true);setMessage('');setError(false);try{await fn();await onChange();if(selected)await readDetail(selected);setMessage(success);}catch(e){if(selected)await readDetail(selected).catch(()=>{});setMessage(e instanceof Error?e.message:'Please try again.');setError(true);}finally{setBusy(false);}}
 function createEvent(ev:FormEvent<HTMLFormElement>){ev.preventDefault();const f=new FormData(ev.currentTarget);void work(async()=>{await post('events/create',{id:requestId.current,title:String(f.get('title')),kind:String(f.get('kind')),location:String(f.get('customLocation')||f.get('location')),gameChannel:Number(f.get('gameChannel')),...(mapPin?{mapPin}:{}),...(f.get('kind')==='Custom'?{pp:Number(f.get('pp'))}:{}),...(f.get('kind')==='Help'?{durationMinutes:Number(f.get('durationMinutes'))}:{starts:localInputTimestamp(String(f.get('starts')))}),description:String(f.get('description')||'')});requestId.current=crypto.randomUUID();createForm.current?.reset();setCreate(false);setKind('Help');setCustomLocation(false);setCustomPP('10');setMapLocation('');setMapPin(null);setSection('schedule');setLimit(50);updateQuery({create:null,section:null,manage:null});},'Event created.');}
 function evidence(ev:FormEvent<HTMLFormElement>){ev.preventDefault();const form=ev.currentTarget;const f=new FormData(form);f.set('eventId',selected!);void work(async()=>{const r=await fetch('/api/events/evidence',{method:'POST',body:f});const j:any=await r.json();if(!r.ok)throw new Error(j.error);form.reset();},'Screenshot uploaded.');}
 const pending=data.events.filter(e=>e.phase==='pending');
 const rows=section==='review'?pending:section==='mine'?data.my_events:section==='history'?data.events.filter(e=>['approved','rejected','cancelled'].includes(e.phase)||e.kind==='Legacy'&&e.status!=='upcoming'):data.events.filter(e=>e.phase==='open'||e.phase==='confirming'||e.phase==='pending'||e.phase==='legacy'&&e.status==='upcoming');
 const visible=rows.filter(e=>filter==='All'||(e.kind==='Legacy'?e.type:e.kind)===filter);
 const sectionTitle=section==='review'?'Awaiting Approval':section==='mine'?'My Events':section==='history'?'Event History':'Schedule';
 const empty=section==='review'?'No events awaiting approval.':section==='mine'?'You have not created or joined any events.':section==='history'?'No completed events yet.':filter==='All'?'No active or upcoming events.':t('No {type} events right now.',{type:eventKindLabel(filter)});
 function chooseApproval(ids:string[]){approvalDraft.current={eventId:selected!,dirty:true,ids};setApprovedIds(ids);}
 async function review(decision:'approved'|'rejected'){const note=reviewNote.current?.value.trim()||'';if(decision==='rejected'&&!note){setMessage('Give a reason for rejecting this event.');setError(true);reviewNote.current?.focus();return;}await work(async()=>{await post('admin/event-review',{eventId:selected,decision,note,approvedMemberIds:decision==='approved'?approvalDraft.current.ids:[]});approvalDraft.current.dirty=false;},'Event review saved.');}
 const reviewing=detail?.event.phase==='pending'&&Boolean(data.member.admin);
 const eligible=detail?[detail.event.created_by,...detail.participants.filter(p=>p.attended).map(p=>p.member_id)]:[];
 const rewardStatus=(memberId:string)=>detail?.reward_reviews?.find(r=>r.member_id===memberId)?.decision;
 const owner=detail?.event.created_by===data.member.id;
 function filterEvents(value:string){setFilter(value);setLimit(50);const url=new URL(location.href);if(value==='All')url.searchParams.delete('type');else url.searchParams.set('type',value);history.replaceState(null,'',url.pathname+url.search);}
 return <div className="pg-events-page">
 <header className="pg-event-heading"><h2>{t("Events")}</h2><button className="pg-button pg-red" aria-haspopup="dialog" onClick={openCreate}>{t("Create Event")}</button></header>
 <div className="pg-event-sections" role="group" aria-label={t("Event sections")}>{[['schedule','Schedule'],['mine','My Events'],['history','History'],...(data.member.admin?[['review','Review']]:[])].map(([value,label])=><button className="pg-event-section" key={value} aria-controls="pg-event-section-panel" aria-pressed={section===value} onClick={()=>changeSection(value)}>{t(label)}{value==='review'&&pending.length>0&&<span className="pg-review-count">{pending.length}</span>}</button>)}</div>
 {message&&!selected&&!create&&<p className={'pg-message'+(error?' pg-error':'')} role={error?'alert':'status'}>{t(message)}</p>}
 <section id="pg-event-section-panel" className="pg-events-surface" aria-label={t(sectionTitle)}>
 <div className="pg-event-list-tools"><h3>{t(sectionTitle)}<span>{visible.length}</span></h3><label className="pg-event-filter"><select name="eventFilter" aria-label={t("Filter by event type")} value={filter} onChange={e=>filterEvents(e.target.value)}><option value="All">{t("Any Event Type")}</option>{EVENT_KINDS.map(value=><option key={value} value={value}>{t(eventKindLabel(value))}</option>)}</select></label></div>
 {visible.length?<ul className="pg-event-summary">{visible.slice(0,limit).map(e=><li key={e.id}><button className="pg-event-open" onClick={()=>open(e.id)}><div><strong>{e.title}</strong><span>{t(typeLabel(e))} · {eventTime(e)}</span>{(e.location||e.game_channel)&&<span>{eventPlace(e)}</span>}<span>{e.creator_name} · {e.signups}{t(" participants")}</span></div><div><b>{e.pp} PP</b><span>{t(eventLabel(e))}</span>{Boolean(e.joined)&&<span className="pg-green">{t("Joined")}</span>}</div></button></li>)}</ul>:<div className="pg-events-empty"><p>{t(empty)}</p></div>}
 {visible.length>limit&&<div className="pg-home-foot"><button className="pg-button" onClick={()=>setLimit(limit+50)}>{t("Show More Events")}</button></div>}
 </section>
 <dialog ref={createDialog} className="pg-dialog pg-create-dialog" aria-labelledby="pg-create-event-title" onCancel={ev=>{ev.preventDefault();closeCreate();}} onClose={()=>{if(create)closeCreate();}}>
 <div className="pg-title"><h3 id="pg-create-event-title">{t("Create Event")}</h3><button className="pg-button" disabled={busy} onClick={closeCreate}>{t("Close")}</button></div>
 {message&&create&&<p className={'pg-message'+(error?' pg-error':'')} role={error?'alert':'status'}>{t(message)}</p>}
 <form ref={createForm} className="pg-form pg-admin-form pg-create-form" onSubmit={createEvent}>
 <label className="pg-field"><span id="pg-event-kind-label">{t("Event Type")}</span><select aria-labelledby="pg-event-kind-label" name="kind" value={kind} onChange={e=>{setKind(e.target.value as EventKind);setCustomLocation(false);setMapPin(null);if(e.target.value==='Demon Tower'||kind==='Demon Tower'||e.target.value==='Custom'||kind==='Custom'){setMapLocation('');}}}>{EVENT_KINDS.map(name=><option key={name} disabled={name!=='Help'&&!data.member.can_host} value={name}>{t(eventKindLabel(name))}</option>)}</select></label>
 <div className="pg-create-reward" aria-live="polite"><strong>{reward>0?new Intl.NumberFormat(localeTag()).format(reward):'—'} <small>PP</small></strong><span>{t("Per member, including creator")}</span></div>
 {!data.member.can_host&&<p className="pg-dim pg-span">{t("Other event types require the Experienced Discord role.")}</p>}
 <label className="pg-field pg-span"><span>{t("Event Name")}</span><input name="title" required maxLength={80} autoComplete="off" placeholder={kind==='Help'?t("Help with a dungeon…"):kind==='Custom'?t("Name your event…"):eventKindLabel(kind)+'…'}/></label>
 {kind==='Demon Tower'?<div className="pg-field"><span>{t("Location")}</span><strong className="pg-fixed-location">{t("Demon Tower")}</strong><input type="hidden" name="location" value="Demon Tower"/></div>:<label className="pg-field"><span id="pg-event-location-label">{t("Location")}</span><select key={kind==='Custom'?'custom':'maps'} aria-labelledby="pg-event-location-label" name="location" required defaultValue="" onChange={e=>{setCustomLocation(e.target.value==='__custom__');setMapLocation(e.target.value);setMapPin(null);}}><option value="" disabled>{t("Choose a Map…")}</option>{kind==='Custom'&&<option value="__custom__">{t("Custom…")}</option>}{EVENT_LOCATIONS.map(group=><optgroup label={t(group.group)} key={group.group}>{group.maps.map(map=><option key={map} value={map}>{mapLabel(map)}</option>)}</optgroup>)}</select></label>}
 <label className="pg-field"><span id="pg-event-channel-label">{t("Channel")}</span><select aria-labelledby="pg-event-channel-label" name="gameChannel" required defaultValue="1">{[1,2,3,4,5,6].map(channel=><option key={channel} value={channel}>CH-{channel}</option>)}</select></label>
 <EventMapPicker key={kind==='Demon Tower'?'Demon Tower':mapLocation} location={kind==='Demon Tower'?'Demon Tower':mapLocation} pin={mapPin} onChange={setMapPin}/>
 {kind==='Custom'&&customLocation&&<label className="pg-field pg-span"><span>{t("Custom Location")}</span><input name="customLocation" required maxLength={80} autoComplete="off" placeholder={t("Meeting point…")}/></label>}
 {kind==='Custom'&&<label className="pg-field pg-span"><span>{t("PP per Member")}</span><input name="pp" type="number" min={1} max={MAX_EVENT_PP} step={1} required autoComplete="off" inputMode="numeric" value={customPP} onChange={e=>setCustomPP(e.target.value)}/></label>}
 {kind==='Help'?<><div className="pg-field"><span>{t("Starts")}</span><strong className="pg-start-now">{t("Now")}</strong></div><label className="pg-field"><span>{t("Duration (minutes)")}</span><input name="durationMinutes" type="number" min={1} max={1440} step={1} defaultValue={60} required autoComplete="off" inputMode="numeric"/></label></>:<label className="pg-field pg-span"><span>{t("Date & Time — ")}{localTimeZone()}</span><input name="starts" type="datetime-local" required autoComplete="off"/></label>}
 <label className="pg-field pg-span"><span>{t("Event Details (optional)")}</span><textarea name="description" rows={2} maxLength={500}/></label>
 <div className="pg-create-rules pg-span"><p>{kind==='Help'?t("2 Help events per guild day. Screenshot required before ending."):t("Ends manually with End Event. Screenshot & attendance confirmation required.")}</p><p>{t("Creator & confirmed participants earn the same PP after admin approval.")}</p></div>
 <div className="pg-create-actions pg-span"><button className="pg-button" type="button" disabled={busy} onClick={closeCreate}>{t("Cancel")}</button><button className="pg-button pg-red" type="submit" disabled={busy||kind!=='Help'&&!data.member.can_host}>{busy?t("Saving…"):kind==='Help'?t("Start Help Event"):t("Schedule Event")}</button></div>
 </form></dialog>
 <dialog ref={dialog} className="pg-dialog pg-event-dialog" aria-labelledby="pg-event-detail-title" onCancel={ev=>{ev.preventDefault();close();}} onClose={()=>{if(selected)close();}}>
 <div className="pg-title"><h3 id="pg-event-detail-title">{detail?.event.title||t("Event Details")}</h3><button className="pg-button" disabled={busy} onClick={close}>{t("Close")}</button></div>
 {message&&selected&&<p className={'pg-message'+(error?' pg-error':'')} role={error?'alert':'status'}>{t(message)}</p>}
 {!detail?<p className="pg-empty" role="status">{t("Loading event…")}</p>:<div className="pg-form pg-event-dialog-body"><div className="pg-event-detail-meta"><span>{t(typeLabel(detail.event))}</span><strong>{detail.event.pp} PP</strong><span>{t(eventLabel(detail.event))}</span></div><details className="pg-event-info" open={detail.event.phase!=='confirming'}><summary>{t("Event Details")}{eventPlace(detail.event)?' · '+eventPlace(detail.event):''}</summary><div><p>{eventTime(detail.event)}{t(" · Hosted by ")}{detail.event.creator_name}</p>{detail.event.kind==='Help'&&detail.event.duration_minutes&&<p className="pg-dim">{t("Expected End: ")}{localTime(detail.event.starts+detail.event.duration_minutes*60)}</p>}{detail.event.kind!=='Help'&&detail.event.kind!=='Legacy'&&<p className="pg-dim">{t("Ends when the creator selects End Event.")}</p>}{eventPlace(detail.event)&&<p className="pg-event-location">{t("Location: ")}<strong>{eventPlace(detail.event)}</strong></p>}{detail.event.description&&<p className="pg-content-description">{detail.event.description}</p>}</div></details>
 {eventMapPin(detail.event)&&<EventMapView pin={eventMapPin(detail.event)!} collapsed={detail.event.phase!=='open'}/>}
 {detail.event.review_note&&<p className="pg-message">{t("Review: ")}{detail.event.review_note}</p>}
 {(detail.event.phase==='open'||detail.event.phase==='legacy'&&detail.event.starts>Date.now()/1000)&&!owner&&<button className="pg-button pg-red" disabled={busy} onClick={()=>void work(()=>post('event',{eventId:selected,joined:!detail.event.joined}),detail.event.joined?'You left the event.':'You joined the event.')}>{data.events.find(e=>e.id===selected)?.joined?t("Leave Event"):t("Join Event")}</button>}
 {['open','legacy'].includes(detail.event.phase)&&detail.event.starts>Date.now()/1000&&<button className="pg-button" onClick={()=>onReminder(detail.event)}>{detail.event.reminder?t("Edit Reminder"):t("Remind Me")}</button>}
 {owner&&detail.event.phase==='open'&&<><button className="pg-button pg-red" disabled={busy||detail.event.starts>Date.now()/1000||(detail.event.kind==='Help'&&!detail.evidence.length)} onClick={()=>void work(()=>post('events/end',{eventId:selected}),'Event ended. Confirm the participants before submitting for approval.')}>{t("End Event")}</button>{detail.event.kind==='Help'&&!detail.evidence.length&&<p className="pg-dim">{t("Upload a screenshot below to enable End Event.")}</p>}</>}
 {(owner||Boolean(data.member.admin))&&detail.event.kind!=='Legacy'&&<details className="pg-event-proof" open={detail.event.phase==='open'||detail.event.phase==='pending'&&Boolean(data.member.admin)}><summary>{t("Screenshot Evidence ")}<span>{detail.evidence.length?t("Uploaded · ")+detail.evidence.length:t("Required")}</span></summary><div className="pg-evidence-grid">{detail.evidence.map(proof=><a key={proof.id} href={'/api/event-evidence/'+proof.id} target="_blank" rel="noopener noreferrer"><img src={'/api/event-evidence/'+proof.id} width={300} height={180} alt={t("Event attendance screenshot")} loading="lazy"/><span>{t("Open Screenshot")}</span></a>)}</div>{!detail.evidence.length&&<p className="pg-dim">{t("No screenshots uploaded.")}</p>}{owner&&['open','confirming'].includes(detail.event.phase)&&detail.event.starts<=Date.now()/1000&&<form onSubmit={evidence} className="pg-proof-form"><label className="pg-field"><span>{t("Upload Screenshot (required, max. 8 MB)")}</span><input type="file" name="screenshot" required accept="image/png,image/jpeg,image/webp"/></label><button type="submit" className="pg-button" disabled={busy||detail.evidence.length>=3}>{t("Upload Screenshot")}</button></form>}</details>}
 <section className="pg-attendance" aria-labelledby="pg-attendance-title"><div className="pg-attendance-heading"><div><h4 id="pg-attendance-title">{reviewing?t("Reward Recipients"):t("Participants")}</h4><span aria-live="polite">{reviewing?approvedIds.length+' / '+eligible.length+t(" selected"):owner&&detail.event.phase==='confirming'?attendedIds.length+' / '+detail.participants.length+t(" selected"):detail.participants.length+t(" participants")}</span></div>{(reviewing||owner&&detail.event.phase==='confirming'&&detail.participants.length>0)&&<button type="button" className="pg-button" disabled={busy} onClick={()=>reviewing?chooseApproval(approvedIds.length===eligible.length?[]:eligible):chooseAttendance(attendedIds.length===detail.participants.length?[]:detail.participants.map(p=>p.member_id))}>{(reviewing?approvedIds.length===eligible.length:attendedIds.length===detail.participants.length)?t("Clear All"):t("Select All")}</button>}</div>
 {detail.event.kind!=='Legacy'&&<div className="pg-attendance-creator">{reviewing?<label className="pg-attendance-choice"><input type="checkbox" checked={approvedIds.includes(detail.event.created_by)} disabled={busy} onChange={e=>chooseApproval(e.target.checked?[...approvedIds,detail.event.created_by]:approvedIds.filter(id=>id!==detail.event.created_by))}/><span><strong>{detail.event.creator_name}</strong><small>{t("Creator")}</small></span><span className="pg-attendance-pp">{detail.event.pp} PP</span></label>:<><strong>{detail.event.creator_name}</strong><span>{t("Creator · ")}{rewardStatus(detail.event.created_by)==='rejected'?t("Rejected · No PP"):detail.event.phase==='approved'?detail.event.pp+t(" PP Awarded"):['rejected','cancelled'].includes(detail.event.phase)?t("Not Awarded"):detail.event.pp+t(" PP after approval")}</span></>}</div>}
 <ul className="pg-participant-list pg-attendance-list" aria-label={t("Event participants")}>{detail.participants.map(p=><li key={p.member_id}>{owner&&detail.event.phase==='confirming'||reviewing?<label className="pg-attendance-choice"><input type="checkbox" checked={(reviewing?approvedIds:attendedIds).includes(p.member_id)} disabled={busy||reviewing&&!p.attended} onChange={ev=>{const ids=reviewing?approvedIds:attendedIds;const next=ev.target.checked?[...ids,p.member_id]:ids.filter(id=>id!==p.member_id);reviewing?chooseApproval(next):chooseAttendance(next);}}/><span><strong>{p.name}</strong><small>{t(p.class)}{reviewing?' · '+(p.attended?t("Confirmed"):t("Not confirmed")):''}</small></span><span className="pg-attendance-pp">{reviewing&&!p.attended?t("No PP"):detail.event.pp+' PP'}</span></label>:<div className="pg-attendance-person"><span><strong>{p.name}</strong><small>{t(p.class)} · {rewardStatus(p.member_id)==='approved'?t("Approved"):rewardStatus(p.member_id)==='rejected'?t("Rejected"):p.attended?t("Confirmed"):t("Signed Up")}</small></span><span className="pg-attendance-pp">{rewardStatus(p.member_id)==='rejected'||['approved','rejected','cancelled'].includes(detail.event.phase)&&!p.attended?t("No PP"):detail.event.pp+' PP'}</span></div>}</li>)}</ul>{!detail.participants.length&&<p className="pg-empty">{t("No participants yet.")}</p>}</section>
 {reviewing&&<div className="pg-review-form"><label className="pg-field"><span>{t("Review Note (required to reject the event)")}</span><textarea ref={reviewNote} name="note" maxLength={500} rows={2}/></label><p className="pg-dim">{t("Only selected members receive ")}{detail.event.pp}{t(" PP. Unselected members receive no PP.")}</p></div>}
 {owner&&['open','confirming'].includes(detail.event.phase)&&<details><summary>{t("Cancel This Event")}</summary><p className="pg-dim">{t("Cancellation awards no PP.")}{detail.event.kind==='Help'&&t(" It counts toward your daily Help limit.")}</p><button className="pg-button" disabled={busy} onClick={()=>void work(()=>post('events/cancel',{eventId:selected}),'Event cancelled.')}>{t("Confirm Cancellation")}</button></details>}
 </div>}
 {detail&&owner&&detail.event.phase==='confirming'&&<footer className="pg-attendance-footer"><div><strong>{attendedIds.length+1}{t(" members · ")}{detail.event.pp}{t(" PP each")}</strong><span>{t("Creator + ")}{attendedIds.length}{t(" selected · Admin approval required")}</span></div><button className="pg-button pg-red" disabled={busy||!detail.evidence.length} onClick={()=>void work(async()=>{await post('events/submit',{eventId:selected,attendedMemberIds:attendanceDraft.current.ids});attendanceDraft.current.dirty=false;},'Submitted for administrator review. PP has not been awarded yet.')}>{busy?t("Submitting…"):t("Submit for Approval")}</button></footer>}
 {detail&&reviewing&&<footer className="pg-attendance-footer pg-review-footer"><div><strong>{approvedIds.length}{t(" members · ")}{detail.event.pp}{t(" PP each")}</strong><span>{eligible.length-approvedIds.length}{t(" excluded from rewards")}</span></div><div className="pg-review-actions"><button className="pg-button" disabled={busy} onClick={()=>void review('rejected')}>{t("Reject Event")}</button><button className="pg-button pg-red" disabled={busy||!approvedIds.length} onClick={()=>void review('approved')}>{busy?t("Saving…"):t("Approve Selected")}</button></div></footer>}
 </dialog></div>;
}
