'use client';
import {useLanguage} from '@/app/language-provider';
import {t,localeTag} from '@/lib/i18n';
import {useState,type ReactNode} from 'react';
import type {BankData} from '@/lib/domain';
const fmt=(n:number)=>n.toLocaleString(localeTag());
const today=()=>new Date(Date.now()+3*3600000).toISOString().slice(0,10);
const date=(s:string)=>new Intl.DateTimeFormat(localeTag(),{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(s+'T12:00:00Z'));
function Panel({title,children}:{title:string;children:ReactNode}){
 useLanguage();return <section className="pg-window"><div className="pg-title">{t(title)}</div>{children}</section>;}
type Props={bank:BankData;admin:boolean;busy:boolean;children:ReactNode;confirm:(title:string,path:string,body:Record<string,unknown>)=>void};
export default function TreasuryPanel({bank,admin,busy,children,confirm}:Props){
 useLanguage();
 const [tab,setTab]=useState(bank.source?'bank':'deposits'),[kind,setKind]=useState('deposit'),[page,setPage]=useState(0),[loanFilter,setLoanFilter]=useState('outstanding');
 const entries=bank.entries.filter(e=>e.kind===kind&&e.status==='recorded').sort((a,b)=>kind==='deposit'?b.amount-a.amount||b.date.localeCompare(a.date):b.date.localeCompare(a.date)),planned=bank.entries.filter(e=>e.status==='planned'),loans=bank.loans.filter(l=>loanFilter==='outstanding'?l.principal>l.repaid:l.principal===l.repaid);
 const amount=(f:FormData,key:string)=>Number(f.get(key)),text=(f:FormData,key:string)=>String(f.get(key)||'');
 return <><div className="pg-bank-tabs" aria-label={t("Treasury sections")}>{[['bank','Guild Bank'],['deposits','My Deposits'],['loans','Loans']].map(([key,label])=><button key={key} className="pg-button" aria-pressed={tab===key} onClick={()=>setTab(key)}>{t(String(label))}</button>)}</div>
 {tab==='deposits'&&children}
 {tab==='bank'&&<><Panel title={t("Guild Bank")}><div className="pg-bank-summary">{[['Available Yang',bank.summary.available],['Planned Expenses',bank.summary.planned],['Outstanding Loans',bank.summary.outstanding]].map(([label,value])=><div key={label}><span>{t(String(label))}</span><strong>{fmt(Number(value))}</strong><small>Yang</small></div>)}</div><p className="pg-table-note">{t("Vault: ")}{fmt(bank.summary.cash)}{t(" Yang · Total deposited: ")}{fmt(bank.summary.deposited)} Yang</p>{!bank.source&&<p className="pg-empty">{t("No guild bank history has been imported yet.")}</p>}</Panel>
 {planned.length>0&&<Panel title={t("Planned Expenses")}><details className="pg-bank-details"><summary>{planned.length}{t(" scheduled expenses · ")}{fmt(bank.summary.planned)}{t(" Yang reserved")}</summary>{planned.map(e=><div className="pg-bank-row" key={e.id}><div><strong>{e.description}</strong><span>{date(e.date)}</span></div><b>{fmt(-e.amount)} Yang</b>{admin&&<button className="pg-button" disabled={busy} onClick={()=>confirm('Confirm Expense Paid','admin/paid-expense',{id:e.id})}>{t("Mark Paid")}</button>}</div>)}<p className="pg-dim">{t("Reserved expenses reduce available funds. Mark paid only after the Yang has been spent.")}</p></details></Panel>}
 <Panel title={t("Bank History")}><div className="pg-bank-controls">{[['deposit','Deposits'],['expense','Expenses']].map(([key,label])=><button className="pg-button" aria-pressed={kind===key} key={key} onClick={()=>{setKind(key);setPage(0);}}>{t(String(label))}</button>)}<span className="pg-dim">{entries.length}{t(" records")}</span></div>{entries.slice(page*10,page*10+10).map(e=><div className="pg-bank-row" key={e.id}><div><strong>{e.kind==='deposit'?e.name:e.description}</strong><span>{date(e.date)}{e.kind==='deposit'&&e.description?' · '+e.description:''}</span></div><b className={e.amount>0?'pg-green':''}>{e.amount>0?'+':''}{fmt(e.amount)} Yang</b></div>)}{!entries.length&&<p className="pg-empty">{t("No records yet.")}</p>}{entries.length>10&&<div className="pg-bank-controls"><button className="pg-button" disabled={page===0} onClick={()=>setPage(p=>p-1)}>{t("Previous")}</button><span>{page+1} / {Math.ceil(entries.length/10)}</span><button className="pg-button" disabled={(page+1)*10>=entries.length} onClick={()=>setPage(p=>p+1)}>{t("Next")}</button></div>}</Panel>
 {bank.source&&<p className="pg-table-note">{t("Imported guild records · ")}<a href={bank.source.url} target="_blank" rel="noopener noreferrer">{t("Original Google Sheet")}</a><br/>{t("Historical Yang payments do not award PP automatically.")}</p>}</>}
 {tab==='loans'&&<><Panel title={t("Guild Loans")}><div className="pg-bank-controls">{[['outstanding','Outstanding'],['repaid','Repaid']].map(([key,label])=><button key={key} className="pg-button" aria-pressed={loanFilter===key} onClick={()=>setLoanFilter(key)}>{t(String(label))}</button>)}</div>{!loans.length&&<p className="pg-empty">{loanFilter==='outstanding'?t("No outstanding loans."):t("No repaid loans yet.")}</p>}{loans.map(l=><div className="pg-loan" key={l.id}><div className="pg-bank-row"><div><strong>{l.borrower}</strong><span>{l.description} · {date(l.issued)}{l.due?t(" · Due ")+date(l.due):''}</span></div><b>{fmt(l.principal-l.repaid)}{t(" Yang left")}</b></div><p className="pg-dim">{t("Borrowed ")}{fmt(l.principal)}{t(" · Repaid ")}{fmt(l.repaid)} Yang</p>{bank.entries.filter(e=>e.loan_id===l.id&&e.kind==='repayment').map(e=><p className="pg-dim" key={e.id}>{date(e.date)} · +{fmt(e.amount)}{t(" Yang repaid")}</p>)}{admin&&l.principal>l.repaid&&<details><summary>{t("Record Repayment")}</summary><form className="pg-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);confirm('Record Loan Repayment','admin/repayment',{loanId:l.id,amount:amount(f,'amount'),date:text(f,'date')});}}><label className="pg-field"><span>{t("Repayment (Yang)")}</span><input type="number" name="amount" required min={1} max={l.principal-l.repaid} step={1}/></label><label className="pg-field"><span>{t("Payment Date")}</span><input type="date" name="date" required defaultValue={today()}/></label><button className="pg-button" disabled={busy}>{t("Record Repayment")}</button></form></details>}</div>)}</Panel>
 {admin&&<Panel title={t("Manage Loans")}><details className="pg-bank-details"><summary>{t("Issue a New Loan")}</summary><form className="pg-form pg-admin-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);confirm('Issue Guild Loan','admin/loan',{borrower:text(f,'borrower'),principal:amount(f,'principal'),description:text(f,'description'),issued:text(f,'issued'),due:text(f,'due')||null});}}><label className="pg-field"><span>{t("Borrower")}</span><input autoComplete="off" spellCheck={false} name="borrower" required maxLength={80}/></label><label className="pg-field"><span>{t("Amount (Yang)")}</span><input name="principal" type="number" required min={1} max={Math.max(1,bank.summary.available)} step={1}/></label><label className="pg-field"><span>{t("Purpose")}</span><input autoComplete="off" name="description" required maxLength={200}/></label><label className="pg-field"><span>{t("Issued Date")}</span><input type="date" name="issued" required defaultValue={today()}/></label><label className="pg-field"><span>{t("Due Date (optional)")}</span><input type="date" name="due"/></label><p className="pg-dim">{t("Available: ")}{fmt(bank.summary.available)}{t(" Yang. Loans do not change PP.")}</p><button className="pg-button" disabled={busy||bank.summary.available<=0}>{t("Issue Loan")}</button></form></details></Panel>}</>}
 </>;
}
