import { sqliteTable, text, integer, primaryKey, check, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const members=sqliteTable('members',{
 id:text('id').primaryKey(), name:text('name').notNull(), class:text('class').notNull(), avatar:text('avatar'), admin:integer('admin').notNull().default(0), canHost:integer('can_host').notNull().default(0), active:integer('active').notNull().default(1), balance:integer('balance').notNull().default(0), reserved:integer('reserved').notNull().default(0), newEvents:integer('new_events').notNull().default(1), created:integer('created').notNull(),
},t=>[check('valid_balance',sql`${t.balance} >= ${t.reserved} AND ${t.reserved} >= 0`)]);
export const sessions=sqliteTable('sessions',{token:text('token').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),expires:integer('expires').notNull(),verified:integer('verified').notNull(),oauth:text('oauth')});
export const oauthStates=sqliteTable('oauth_states',{state:text('state').primaryKey(),expires:integer('expires').notNull()});
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const items=sqliteTable('items',{id:text('id').primaryKey(),name:text('name').notNull(),icon:text('icon').notNull(),height:integer('height').notNull(),level:integer('level'),classes:text('classes').notNull(),created:integer('created').notNull()});
export const events=sqliteTable('events',{id:text('id').primaryKey(),title:text('title').notNull(),type:text('type').notNull(),starts:integer('starts').notNull(),pp:integer('pp').notNull(),description:text('description').notNull(),status:text('status').notNull().default('upcoming'),kind:text('kind').notNull().default('Legacy'),phase:text('phase').notNull().default('legacy'),creationDay:text('creation_day'),durationMinutes:integer('duration_minutes'),location:text('location').notNull().default(''),gameChannel:integer('game_channel'),ended:integer('ended'),submitted:integer('submitted'),reviewed:integer('reviewed'),reviewedBy:text('reviewed_by').references(()=>members.id),reviewNote:text('review_note').notNull().default(''),createdBy:text('created_by').notNull().references(()=>members.id),created:integer('created').notNull()},t=>[index('event_owner_phase').on(t.createdBy,t.phase),index('event_owner_day').on(t.createdBy,t.creationDay,t.kind),check('valid_event',sql`${t.pp} >= 0 AND ${t.type} IN ('PvE','PvP') AND ${t.status} IN ('upcoming','completed','cancelled')`)]);
export const eventMembers=sqliteTable('event_members',{eventId:text('event_id').notNull().references(()=>events.id),memberId:text('member_id').notNull().references(()=>members.id),joined:integer('joined').notNull().default(0),attended:integer('attended').notNull().default(0),reminder:integer('reminder'),created:integer('created').notNull()},t=>[primaryKey({columns:[t.eventId,t.memberId]})]);
export const deposits=sqliteTable('deposits',{id:text('id').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),yang:integer('yang').notNull(),pp:integer('pp').notNull(),kind:text('kind').notNull(),week:text('week'),note:text('note').notNull(),status:text('status').notNull().default('pending'),reviewedBy:text('reviewed_by').references(()=>members.id),reviewed:integer('reviewed'),created:integer('created').notNull()},t=>[uniqueIndex('one_weekly_deposit').on(t.memberId,t.week).where(sql`${t.status} IN ('pending','approved')`),check('valid_deposit',sql`${t.yang} > 0 AND ${t.pp} >= 0 AND ${t.status} IN ('pending','approved','rejected') AND ${t.kind} IN ('weekly','donation')`)]);
export const auctions=sqliteTable('auctions',{id:text('id').primaryKey(),itemId:text('item_id').notNull().references(()=>items.id),upgrade:integer('upgrade').notNull(),quantity:integer('quantity').notNull().default(1),source:text('source').notNull(),bonuses:text('bonuses').notNull(),minimum:integer('minimum').notNull(),increment:integer('increment').notNull(),current:integer('current').notNull().default(0),winner:text('winner').references(()=>members.id),starts:integer('starts').notNull(),ends:integer('ends').notNull(),status:text('status').notNull().default('active'),createdBy:text('created_by').notNull().references(()=>members.id),created:integer('created').notNull()},t=>[check('valid_auction',sql`${t.minimum} > 0 AND ${t.increment} > 0 AND ${t.ends} > ${t.starts} AND ${t.current} >= 0 AND ${t.upgrade} BETWEEN 0 AND 9 AND ${t.quantity} > 0 AND ${t.status} IN ('active','closed','cancelled')`)]);
export const bids=sqliteTable('bids',{id:text('id').primaryKey(),auctionId:text('auction_id').notNull().references(()=>auctions.id),memberId:text('member_id').notNull().references(()=>members.id),amount:integer('amount').notNull(),created:integer('created').notNull()});
export const ledger=sqliteTable('ledger',{id:text('id').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),amount:integer('amount').notNull(),category:text('category').notNull(),label:text('label').notNull(),created:integer('created').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),action:text('action').notNull(),target:text('target').notNull(),created:integer('created').notNull()});
export const subscriptions=sqliteTable('subscriptions',{endpoint:text('endpoint').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),p256dh:text('p256dh').notNull(),auth:text('auth').notNull(),created:integer('created').notNull()});
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),eventId:text('event_id').notNull().references(()=>events.id),kind:text('kind').notNull(),status:text('status').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),leased:integer('leased'),created:integer('created').notNull()});
export const bankSource=sqliteTable('bank_source',{key:text('key').primaryKey(),batch:text('batch').notNull(),url:text('url').notNull(),title:text('title').notNull(),issues:text('issues').notNull(),imported:integer('imported').notNull(),importedBy:text('imported_by').notNull().references(()=>members.id)});
export const bankPeople=sqliteTable('bank_people',{id:text('id').primaryKey(),batch:text('batch').notNull(),name:text('name').notNull(),class:text('class').notNull(),yang:integer('yang').notNull(),active:integer('active').notNull()},t=>[check('valid_bank_person',sql`${t.yang}>=0 AND ${t.active} IN (0,1)`)]);
export const guildLoans=sqliteTable('guild_loans',{id:text('id').primaryKey(),batch:text('batch'),borrower:text('borrower').notNull(),principal:integer('principal').notNull(),repaid:integer('repaid').notNull().default(0),description:text('description').notNull(),issued:text('issued').notNull(),due:text('due'),created:integer('created').notNull(),createdBy:text('created_by').notNull().references(()=>members.id)},t=>[check('valid_loan',sql`${t.principal}>0 AND ${t.repaid}>=0 AND ${t.repaid}<=${t.principal}`)]);
export const bankEntries=sqliteTable('bank_entries',{id:text('id').primaryKey(),batch:text('batch'),kind:text('kind').notNull(),status:text('status').notNull().default('recorded'),name:text('name').notNull(),amount:integer('amount').notNull(),date:text('date').notNull(),description:text('description').notNull(),sourceRow:integer('source_row'),sourceTab:text('source_tab'),loanId:text('loan_id').references(()=>guildLoans.id),createdBy:text('created_by').references(()=>members.id)},t=>[check('valid_bank_entry',sql`${t.amount}<>0 AND ${t.kind} IN ('deposit','expense','loan','repayment')`)]);

export const eventEvidence=sqliteTable('event_evidence',{id:text('id').primaryKey(),eventId:text('event_id').notNull().references(()=>events.id),uploadedBy:text('uploaded_by').notNull().references(()=>members.id),filename:text('filename').notNull(),contentType:text('content_type').notNull(),created:integer('created').notNull()},t=>[index('evidence_event').on(t.eventId)]);

export const sheetSync=sqliteTable('sheet_sync',{key:text('key').primaryKey(),batch:text('batch'),checked:integer('checked').notNull().default(0),attempted:integer('attempted').notNull().default(0),lease:integer('lease').notNull().default(0),error:text('error').notNull().default('')});
export const sheetPeople=sqliteTable('sheet_people',{batch:text('batch').notNull(),nameKey:text('name_key').notNull(),name:text('name').notNull(),yang:integer('yang').notNull()},t=>[primaryKey({columns:[t.batch,t.nameKey]}),check('sheet_person_amount',sql`${t.yang}>=0`)]);
export const sheetDeposits=sqliteTable('sheet_deposits',{batch:text('batch').notNull(),row:integer('row').notNull(),nameKey:text('name_key').notNull(),name:text('name').notNull(),date:text('date').notNull(),yang:integer('yang').notNull(),note:text('note').notNull()},t=>[primaryKey({columns:[t.batch,t.row]}),index('sheet_deposit_name_date').on(t.batch,t.nameKey,t.date),check('sheet_deposit_amount',sql`${t.yang}>0`)]);
export const weeklyRewards=sqliteTable('weekly_rewards',{memberId:text('member_id').notNull().references(()=>members.id),week:text('week').notNull(),pp:integer('pp').notNull(),yang:integer('yang').notNull(),batch:text('batch').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.memberId,t.week]}),check('weekly_reward_amount',sql`${t.pp}>=0 AND ${t.yang}>0`)]);

// Frozen reset-time totals remain available until the matching Discord member signs in.
export const contributionBaselines=sqliteTable('contribution_baselines',{nameKey:text('name_key').primaryKey(),name:text('name').notNull(),yang:integer('yang').notNull(),pp:integer('pp').notNull(),week:text('week').notNull(),weeklyPp:integer('weekly_pp').notNull(),unit:integer('unit').notNull(),rate:integer('rate').notNull(),sourceBatch:text('source_batch').notNull(),created:integer('created').notNull()},t=>[check('baseline_amount',sql`${t.yang}>=0 AND ${t.unit}>0 AND ${t.rate}>=0 AND ${t.pp}=CAST(${t.yang}*1.0/${t.unit}*${t.rate} AS INTEGER) AND ${t.weeklyPp} BETWEEN 0 AND ${t.rate} AND ${t.weeklyPp}<=${t.pp}`)]);
export const contributionBaselineClaims=sqliteTable('contribution_baseline_claims',{nameKey:text('name_key').primaryKey().references(()=>contributionBaselines.nameKey),memberId:text('member_id').notNull().unique().references(()=>members.id),created:integer('created').notNull()});

export const eventRewardReviews=sqliteTable('event_reward_reviews',{eventId:text('event_id').notNull().references(()=>events.id),memberId:text('member_id').notNull().references(()=>members.id),decision:text('decision').notNull(),reviewedBy:text('reviewed_by').notNull().references(()=>members.id),reviewed:integer('reviewed').notNull()},t=>[primaryKey({columns:[t.eventId,t.memberId]}),check('valid_reward_decision',sql`${t.decision} IN ('approved','rejected')`)]);

export const discordAnnouncements=sqliteTable('discord_announcements',{eventId:text('event_id').primaryKey().references(()=>events.id),channelId:text('channel_id').notNull(),status:text('status').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),leased:integer('leased'),messageId:text('message_id'),created:integer('created').notNull()},t=>[check('valid_announcement_status',sql`${t.status} IN ('pending','sending','sent','skipped','failed') AND ${t.attempts} >= 0`)]);

// One editable card and one final receipt per entity. Triggers enqueue in the same transaction.
export const discordCards=sqliteTable('discord_cards',{id:text('id').primaryKey(),entityType:text('entity_type').notNull(),entityId:text('entity_id').notNull(),purpose:text('purpose').notNull().default('card'),part:integer('part').notNull().default(0),channelId:text('channel_id'),messageId:text('message_id'),status:text('status').notNull().default('pending'),revision:integer('revision').notNull().default(1),sentRevision:integer('sent_revision').notNull().default(0),attempts:integer('attempts').notNull().default(0),leaseToken:text('lease_token'),leased:integer('leased'),nextAttempt:integer('next_attempt').notNull().default(0),nextRefresh:integer('next_refresh'),created:integer('created').notNull()},t=>[uniqueIndex('discord_card_entity_purpose').on(t.entityType,t.entityId,t.purpose,t.part),index('discord_card_queue').on(t.status,t.nextAttempt),check('valid_discord_card',sql`${t.entityType} IN ('event','auction') AND ${t.purpose} IN ('card','result') AND ${t.status} IN ('pending','sending','sent','failed','skipped') AND ${t.revision}>0 AND ${t.sentRevision}>=0 AND ${t.attempts}>=0`)]);
